// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/advanced.dart';
import 'api/image.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BatchResizeItem dco_decode_batch_resize_item(dynamic raw);

  @protected
  BeautyLookPreset dco_decode_beauty_look_preset(dynamic raw);

  @protected
  BeautyParams dco_decode_beauty_params(dynamic raw);

  @protected
  BlendMode dco_decode_blend_mode(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BeautyParams dco_decode_box_autoadd_beauty_params(dynamic raw);

  @protected
  DrawCircle dco_decode_box_autoadd_draw_circle(dynamic raw);

  @protected
  DrawLine dco_decode_box_autoadd_draw_line(dynamic raw);

  @protected
  ImageFilter dco_decode_box_autoadd_image_filter(dynamic raw);

  @protected
  RgbaImageBuffer dco_decode_box_autoadd_rgba_image_buffer(dynamic raw);

  @protected
  SwipeLookExtrasDto dco_decode_box_autoadd_swipe_look_extras_dto(dynamic raw);

  @protected
  TextOverlay dco_decode_box_autoadd_text_overlay(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DrawCircle dco_decode_draw_circle(dynamic raw);

  @protected
  DrawLine dco_decode_draw_line(dynamic raw);

  @protected
  EditOp dco_decode_edit_op(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FilterPreset dco_decode_filter_preset(dynamic raw);

  @protected
  GpuComputeInfo dco_decode_gpu_compute_info(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImageFilter dco_decode_image_filter(dynamic raw);

  @protected
  ImageInfo dco_decode_image_info(dynamic raw);

  @protected
  LipTintPreset dco_decode_lip_tint_preset(dynamic raw);

  @protected
  List<BatchResizeItem> dco_decode_list_batch_resize_item(dynamic raw);

  @protected
  List<EditOp> dco_decode_list_edit_op(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MoodFilterPreset dco_decode_mood_filter_preset(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  OutputFormat dco_decode_output_format(dynamic raw);

  @protected
  PreviewQuality dco_decode_preview_quality(dynamic raw);

  @protected
  ProcessingBackend dco_decode_processing_backend(dynamic raw);

  @protected
  ProgressiveDecodeResult dco_decode_progressive_decode_result(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_usize_usize(dynamic raw);

  @protected
  ResizeAlgorithm dco_decode_resize_algorithm(dynamic raw);

  @protected
  RgbaImageBuffer dco_decode_rgba_image_buffer(dynamic raw);

  @protected
  Rotation dco_decode_rotation(dynamic raw);

  @protected
  SwipeLookExtrasDto dco_decode_swipe_look_extras_dto(dynamic raw);

  @protected
  SwipeLookPreset dco_decode_swipe_look_preset(dynamic raw);

  @protected
  TextOverlay dco_decode_text_overlay(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BatchResizeItem sse_decode_batch_resize_item(SseDeserializer deserializer);

  @protected
  BeautyLookPreset sse_decode_beauty_look_preset(SseDeserializer deserializer);

  @protected
  BeautyParams sse_decode_beauty_params(SseDeserializer deserializer);

  @protected
  BlendMode sse_decode_blend_mode(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BeautyParams sse_decode_box_autoadd_beauty_params(
    SseDeserializer deserializer,
  );

  @protected
  DrawCircle sse_decode_box_autoadd_draw_circle(SseDeserializer deserializer);

  @protected
  DrawLine sse_decode_box_autoadd_draw_line(SseDeserializer deserializer);

  @protected
  ImageFilter sse_decode_box_autoadd_image_filter(SseDeserializer deserializer);

  @protected
  RgbaImageBuffer sse_decode_box_autoadd_rgba_image_buffer(
    SseDeserializer deserializer,
  );

  @protected
  SwipeLookExtrasDto sse_decode_box_autoadd_swipe_look_extras_dto(
    SseDeserializer deserializer,
  );

  @protected
  TextOverlay sse_decode_box_autoadd_text_overlay(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DrawCircle sse_decode_draw_circle(SseDeserializer deserializer);

  @protected
  DrawLine sse_decode_draw_line(SseDeserializer deserializer);

  @protected
  EditOp sse_decode_edit_op(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FilterPreset sse_decode_filter_preset(SseDeserializer deserializer);

  @protected
  GpuComputeInfo sse_decode_gpu_compute_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImageFilter sse_decode_image_filter(SseDeserializer deserializer);

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer);

  @protected
  LipTintPreset sse_decode_lip_tint_preset(SseDeserializer deserializer);

  @protected
  List<BatchResizeItem> sse_decode_list_batch_resize_item(
    SseDeserializer deserializer,
  );

  @protected
  List<EditOp> sse_decode_list_edit_op(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MoodFilterPreset sse_decode_mood_filter_preset(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  OutputFormat sse_decode_output_format(SseDeserializer deserializer);

  @protected
  PreviewQuality sse_decode_preview_quality(SseDeserializer deserializer);

  @protected
  ProcessingBackend sse_decode_processing_backend(SseDeserializer deserializer);

  @protected
  ProgressiveDecodeResult sse_decode_progressive_decode_result(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_usize_usize(SseDeserializer deserializer);

  @protected
  ResizeAlgorithm sse_decode_resize_algorithm(SseDeserializer deserializer);

  @protected
  RgbaImageBuffer sse_decode_rgba_image_buffer(SseDeserializer deserializer);

  @protected
  Rotation sse_decode_rotation(SseDeserializer deserializer);

  @protected
  SwipeLookExtrasDto sse_decode_swipe_look_extras_dto(
    SseDeserializer deserializer,
  );

  @protected
  SwipeLookPreset sse_decode_swipe_look_preset(SseDeserializer deserializer);

  @protected
  TextOverlay sse_decode_text_overlay(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_batch_resize_item(
    BatchResizeItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_beauty_look_preset(
    BeautyLookPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_beauty_params(BeautyParams self, SseSerializer serializer);

  @protected
  void sse_encode_blend_mode(BlendMode self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_beauty_params(
    BeautyParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_draw_circle(
    DrawCircle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_draw_line(
    DrawLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_filter(
    ImageFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rgba_image_buffer(
    RgbaImageBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swipe_look_extras_dto(
    SwipeLookExtrasDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_text_overlay(
    TextOverlay self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_draw_circle(DrawCircle self, SseSerializer serializer);

  @protected
  void sse_encode_draw_line(DrawLine self, SseSerializer serializer);

  @protected
  void sse_encode_edit_op(EditOp self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_filter_preset(FilterPreset self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_compute_info(
    GpuComputeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_image_filter(ImageFilter self, SseSerializer serializer);

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_lip_tint_preset(LipTintPreset self, SseSerializer serializer);

  @protected
  void sse_encode_list_batch_resize_item(
    List<BatchResizeItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_edit_op(List<EditOp> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mood_filter_preset(
    MoodFilterPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_output_format(OutputFormat self, SseSerializer serializer);

  @protected
  void sse_encode_preview_quality(
    PreviewQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processing_backend(
    ProcessingBackend self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_progressive_decode_result(
    ProgressiveDecodeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resize_algorithm(
    ResizeAlgorithm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rgba_image_buffer(
    RgbaImageBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rotation(Rotation self, SseSerializer serializer);

  @protected
  void sse_encode_swipe_look_extras_dto(
    SwipeLookExtrasDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swipe_look_preset(
    SwipeLookPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_text_overlay(TextOverlay self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
