// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'image.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply_single_op_cpu`, `encode_after_edit_rgba`, `encode_after_edit`, `is_gpu_capable`, `process`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `hash`, `hash`, `hash`

/// Resizes an image file and encodes the result in the specified format and quality.
Uint8List resizeImage({
  required List<int> bytes,
  required int width,
  required int height,
  required ResizeAlgorithm algorithm,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageResizeImage(
  bytes: bytes,
  width: width,
  height: height,
  algorithm: algorithm,
  format: format,
  quality: quality,
  fixExif: fixExif,
  backend: backend,
);

/// Creates a fast thumbnail for an image. Fits the image within `max_edge` bounding box.
Uint8List createThumbnail({
  required List<int> bytes,
  required int maxEdge,
  required OutputFormat format,
  required int quality,
  required ResizeAlgorithm algorithm,
  required bool fixExif,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageCreateThumbnail(
  bytes: bytes,
  maxEdge: maxEdge,
  format: format,
  quality: quality,
  algorithm: algorithm,
  fixExif: fixExif,
  backend: backend,
);

/// Crops a rectangular area of an image file.
Uint8List cropImage({
  required List<int> bytes,
  required int x,
  required int y,
  required int width,
  required int height,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageCropImage(
  bytes: bytes,
  x: x,
  y: y,
  width: width,
  height: height,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

/// Rotates or flips an image file.
Uint8List rotateImage({
  required List<int> bytes,
  required Rotation rotation,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageRotateImage(
  bytes: bytes,
  rotation: rotation,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

/// Rewrites the image file so that pixels match the physical EXIF orientation, clearing the EXIF tag.
Uint8List fixExifOrientation({
  required List<int> bytes,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageFixExifOrientation(
  bytes: bytes,
  format: format,
  quality: quality,
);

/// Reads the raw EXIF orientation value from the image metadata.
int? readExifOrientation({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageReadExifOrientation(bytes: bytes);

/// Re-compresses an image file with a specified quality and output format.
Uint8List compressImage({
  required List<int> bytes,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageCompressImage(
  bytes: bytes,
  format: format,
  quality: quality,
);

/// Applies a basic filter or adjustment (brightness, blur, etc.) to an image file.
/// Studio filters (Mood, SwipeLook, LutPng, SkinSmooth, Beauty) return an error when
/// called without the `image_forge` package.
Uint8List applyFilter({
  required List<int> bytes,
  required ImageFilter filter,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageApplyFilter(
  bytes: bytes,
  filter: filter,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

/// Overlays a watermark image onto a base image at the specified pixel coordinates.
Uint8List addWatermark({
  required List<int> baseBytes,
  required List<int> overlayBytes,
  required int x,
  required int y,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageAddWatermark(
  baseBytes: baseBytes,
  overlayBytes: overlayBytes,
  x: x,
  y: y,
  format: format,
  quality: quality,
);

/// Renders a single line of text directly onto the image.
Uint8List drawTextOnImage({
  required List<int> bytes,
  required TextOverlay overlay,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageDrawTextOnImage(
  bytes: bytes,
  overlay: overlay,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

/// Draws a vector line directly onto the image.
Uint8List drawLineOnImage({
  required List<int> bytes,
  required DrawLine line,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageDrawLineOnImage(
  bytes: bytes,
  line: line,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

/// Draws a vector circle directly onto the image.
Uint8List drawCircleOnImage({
  required List<int> bytes,
  required DrawCircle circle,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageDrawCircleOnImage(
  bytes: bytes,
  circle: circle,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

/// Resizes multiple images concurrently in parallel (using rayon).
List<Uint8List> batchResizeImages({
  required List<BatchResizeItem> items,
  required ResizeAlgorithm algorithm,
  required OutputFormat format,
  required int quality,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageBatchResizeImages(
  items: items,
  algorithm: algorithm,
  format: format,
  quality: quality,
  backend: backend,
);

/// Composites an overlay image onto a base image using standard blend modes.
Uint8List overlayImage({
  required List<int> baseBytes,
  required List<int> overlayBytes,
  required int x,
  required int y,
  required BlendMode blendMode,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageOverlayImage(
  baseBytes: baseBytes,
  overlayBytes: overlayBytes,
  x: x,
  y: y,
  blendMode: blendMode,
  format: format,
  quality: quality,
);

/// Computes a BlurHash string from raw image bytes.
String encodeBlurhash({
  required List<int> bytes,
  required int componentsX,
  required int componentsY,
}) => RustLib.instance.api.crateApiImageEncodeBlurhash(
  bytes: bytes,
  componentsX: componentsX,
  componentsY: componentsY,
);

/// Decodes a BlurHash string back into compressed image bytes.
Uint8List decodeBlurhash({
  required String hash,
  required int width,
  required int height,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageDecodeBlurhash(
  hash: hash,
  width: width,
  height: height,
  format: format,
  quality: quality,
);

RgbaImageBuffer applyEditPipeline({
  required RgbaImageBuffer buffer,
  required List<EditOp> ops,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageApplyEditPipeline(
  buffer: buffer,
  ops: ops,
  backend: backend,
);

/// Dummy function to force the code generator to expose BeautyLookPreset and SwipeLookExtrasDto
void dummyForCodegenExtras({
  required SwipeLookExtrasDto a,
  required BeautyLookPreset b,
}) => RustLib.instance.api.crateApiImageDummyForCodegenExtras(a: a, b: b);

/// Batch resize input payload.
class BatchResizeItem {
  final Uint8List bytes;
  final int width;
  final int height;

  const BatchResizeItem({
    required this.bytes,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => bytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchResizeItem &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height;
}

/// One-tap beauty look preset.
enum BeautyLookPreset { natural, soft, glow, glam, clear, peach, bold }

/// Regional beauty parameters — used by face beauty pipeline in image_forge.
class BeautyParams {
  final double skinSmooth;
  final double eyeBrighten;
  final LipTintPreset lipTint;
  final double lipTintStrength;
  final double lipPlump;
  final double blush;
  final double underEye;
  final double teethWhiten;
  final double skinPreserveDetail;
  final double eyeEnlarge;
  final double jawSlim;
  final double noseSlim;
  final double faceSlim;
  final double chinVshape;

  const BeautyParams({
    required this.skinSmooth,
    required this.eyeBrighten,
    required this.lipTint,
    required this.lipTintStrength,
    required this.lipPlump,
    required this.blush,
    required this.underEye,
    required this.teethWhiten,
    required this.skinPreserveDetail,
    required this.eyeEnlarge,
    required this.jawSlim,
    required this.noseSlim,
    required this.faceSlim,
    required this.chinVshape,
  });

  static Future<BeautyParams> default_() =>
      RustLib.instance.api.crateApiImageBeautyParamsDefault();

  @override
  int get hashCode =>
      skinSmooth.hashCode ^
      eyeBrighten.hashCode ^
      lipTint.hashCode ^
      lipTintStrength.hashCode ^
      lipPlump.hashCode ^
      blush.hashCode ^
      underEye.hashCode ^
      teethWhiten.hashCode ^
      skinPreserveDetail.hashCode ^
      eyeEnlarge.hashCode ^
      jawSlim.hashCode ^
      noseSlim.hashCode ^
      faceSlim.hashCode ^
      chinVshape.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BeautyParams &&
          runtimeType == other.runtimeType &&
          skinSmooth == other.skinSmooth &&
          eyeBrighten == other.eyeBrighten &&
          lipTint == other.lipTint &&
          lipTintStrength == other.lipTintStrength &&
          lipPlump == other.lipPlump &&
          blush == other.blush &&
          underEye == other.underEye &&
          teethWhiten == other.teethWhiten &&
          skinPreserveDetail == other.skinPreserveDetail &&
          eyeEnlarge == other.eyeEnlarge &&
          jawSlim == other.jawSlim &&
          noseSlim == other.noseSlim &&
          faceSlim == other.faceSlim &&
          chinVshape == other.chinVshape;
}

/// Composite blend modes.
enum BlendMode { normal, multiply, screen, overlay, add }

/// Vector circle coordinates and styles.
class DrawCircle {
  final int centerX;
  final int centerY;
  final int radius;
  final int colorR;
  final int colorG;
  final int colorB;
  final int colorA;

  const DrawCircle({
    required this.centerX,
    required this.centerY,
    required this.radius,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
  });

  @override
  int get hashCode =>
      centerX.hashCode ^
      centerY.hashCode ^
      radius.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawCircle &&
          runtimeType == other.runtimeType &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          radius == other.radius &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA;
}

/// Vector line coordinates and styles.
class DrawLine {
  final int x0;
  final int y0;
  final int x1;
  final int y1;
  final int colorR;
  final int colorG;
  final int colorB;
  final int colorA;

  const DrawLine({
    required this.x0,
    required this.y0,
    required this.x1,
    required this.y1,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
  });

  @override
  int get hashCode =>
      x0.hashCode ^
      y0.hashCode ^
      x1.hashCode ^
      y1.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawLine &&
          runtimeType == other.runtimeType &&
          x0 == other.x0 &&
          y0 == other.y0 &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA;
}

@freezed
sealed class EditOp with _$EditOp {
  const EditOp._();

  const factory EditOp.filter({required ImageFilter filter}) = EditOp_Filter;
  const factory EditOp.resize({
    required int width,
    required int height,
    required ResizeAlgorithm algorithm,
  }) = EditOp_Resize;
  const factory EditOp.crop({
    required int x,
    required int y,
    required int width,
    required int height,
  }) = EditOp_Crop;
  const factory EditOp.rotate({required Rotation rotation}) = EditOp_Rotate;
}

/// Filter presets applied globally to color grade the image.
enum FilterPreset {
  neue,
  lix,
  ryo,
  lofi,
  pastelPink,
  golden,
  cali,
  dramatic,
  firenze,
  obsidian,
  duotoneViolette,
  duotoneHorizon,
  duotoneLilac,
  duotoneOchre,
}

/// Diagnostics metadata about the active GPU device.
class GpuComputeInfo {
  final bool available;
  final String api;
  final String device;

  const GpuComputeInfo({
    required this.available,
    required this.api,
    required this.device,
  });

  @override
  int get hashCode => available.hashCode ^ api.hashCode ^ device.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpuComputeInfo &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          api == other.api &&
          device == other.device;
}

@freezed
sealed class ImageFilter with _$ImageFilter {
  const ImageFilter._();

  /// Gaussian or box blur.
  const factory ImageFilter.blur({required int radius}) = ImageFilter_Blur;

  /// High-pass sharpening.
  const factory ImageFilter.sharpen() = ImageFilter_Sharpen;

  /// Adjust brightness (range: -255 to 255).
  const factory ImageFilter.brightness({required int amount}) =
      ImageFilter_Brightness;

  /// Adjust contrast (range: 0.0 to 10.0, 1.0 is identity).
  const factory ImageFilter.contrast({required double amount}) =
      ImageFilter_Contrast;

  /// Adjust color saturation (range: 0.0 to 10.0, 1.0 is identity).
  const factory ImageFilter.saturation({required double amount}) =
      ImageFilter_Saturation;

  /// Rotate hue in degrees (range: 0.0 to 360.0).
  const factory ImageFilter.hueRotate({required double degrees}) =
      ImageFilter_HueRotate;

  /// Artistic oil painting effect.
  const factory ImageFilter.oil({
    required int radius,
    required double intensity,
  }) = ImageFilter_Oil;

  /// Frosted glass blurring effect.
  const factory ImageFilter.frostedGlass() = ImageFilter_FrostedGlass;

  /// Pixelation effect with custom cell size.
  const factory ImageFilter.pixelize({required int size}) =
      ImageFilter_Pixelize;

  /// Invert colors based on threshold/solarization.
  const factory ImageFilter.solarize() = ImageFilter_Solarize;

  /// Classic presets (Neue, Lofi, Firenze, etc.) with custom strength (0.0 to 1.0).
  const factory ImageFilter.preset({
    required FilterPreset preset,
    required double strength,
  }) = ImageFilter_Preset;

  /// Color temperature shift (-100 cool ... +100 warm).
  const factory ImageFilter.warmth({required double amount}) =
      ImageFilter_Warmth;

  /// Blend toward neutral gray (0 = none, 1 = max fade).
  const factory ImageFilter.fade({required double amount}) = ImageFilter_Fade;

  /// Radial edge darkening (0 = none, 1 = strong).
  const factory ImageFilter.vignette({required double amount}) =
      ImageFilter_Vignette;

  /// Recover/compress bright tones (-100 ... +100).
  const factory ImageFilter.highlights({required double amount}) =
      ImageFilter_Highlights;

  /// Lift/crush dark tones (-100 ... +100).
  const factory ImageFilter.shadows({required double amount}) =
      ImageFilter_Shadows;

  /// Local clarity / micro-contrast (-100 ... +100).
  const factory ImageFilter.structure({required double amount}) =
      ImageFilter_Structure;

  /// Swipe mood filter (Instagram-style global grade) — requires image_forge.
  const factory ImageFilter.mood({
    required MoodFilterPreset preset,
    required double strength,
  }) = ImageFilter_Mood;

  /// Combo swipe look (global grade from [SwipeLookPreset] — beauty in separate slot) — requires image_forge.
  const factory ImageFilter.swipeLook({
    required SwipeLookPreset preset,
    required double strength,
  }) = ImageFilter_SwipeLook;

  /// Authentic 3D LUT PNG filter (Hald CLUT representation) — requires image_forge.
  const factory ImageFilter.lutPng({
    required Uint8List pngBytes,
    required double strength,
  }) = ImageFilter_LutPng;

  /// Regional skin smooth (mask applied separately in session / GPU pass) — requires image_forge.
  const factory ImageFilter.skinSmooth({required double strength}) =
      ImageFilter_SkinSmooth;

  /// Regional beauty (skin, eyes, lips, blush) — mask + landmarks in session — requires image_forge.
  const factory ImageFilter.beauty({required BeautyParams params}) =
      ImageFilter_Beauty;
}

/// High-level format and EXIF info for a queried image.
class ImageInfo {
  final int width;
  final int height;
  final String? format;
  final int? exifOrientation;

  const ImageInfo({
    required this.width,
    required this.height,
    this.format,
    this.exifOrientation,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      exifOrientation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          exifOrientation == other.exifOrientation;
}

/// Lip color swatch for regional tint.
enum LipTintPreset {
  none,
  nude,
  rose,
  berry,
  coral,
  red;

  static Future<LipTintPreset> default_() =>
      RustLib.instance.api.crateApiImageLipTintPresetDefault();
}

/// Instagram-style mood filters (requires image_forge for implementation).
enum MoodFilterPreset {
  rose,
  clarendon,
  juno,
  valencia,
  lark,
  reyes,
  gingham,
  loFi,
  moon,
  aden,
  perpetua,
  mayfair,
  hudson,
  sierra,
  willow,
  inkwell,
}

/// The image format for output compression.
enum OutputFormat { jpeg, png, webP, avif }

/// Quality vs Speed choice for interactive previews.
enum PreviewQuality { fast, quality }

/// Processing backend: CPU (SIMD) or GPU (Metal/Vulkan via wgpu).
enum ProcessingBackend { cpu, gpu, auto }

/// Progressive decoding results containing a fast preview and the full image buffer.
class ProgressiveDecodeResult {
  final ImageInfo info;
  final RgbaImageBuffer previewRgba;
  final RgbaImageBuffer buffer;

  const ProgressiveDecodeResult({
    required this.info,
    required this.previewRgba,
    required this.buffer,
  });

  @override
  int get hashCode => info.hashCode ^ previewRgba.hashCode ^ buffer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressiveDecodeResult &&
          runtimeType == other.runtimeType &&
          info == other.info &&
          previewRgba == other.previewRgba &&
          buffer == other.buffer;
}

/// Image resizing algorithms, ranging from fast/nearest-neighbor to high-quality Lanczos.
enum ResizeAlgorithm { nearest, box, hamming, catmullRom, mitchell, lanczos3 }

/// Raw RGBA buffer for chained edits without re-decoding.
class RgbaImageBuffer {
  final int width;
  final int height;
  final Uint8List pixels;

  const RgbaImageBuffer({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RgbaImageBuffer &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// Rotations and mirror/flip transformations.
enum Rotation { rotate90, rotate180, rotate270, flipHorizontal, flipVertical }

/// Post-grade extras applied during combo looks (such as overlay glow or grain).
class SwipeLookExtrasDto {
  final double glow;
  final double grain;
  final double sharpen;
  final double skinPreserveDetail;
  final double halation;
  final double rgbSplit;

  const SwipeLookExtrasDto({
    required this.glow,
    required this.grain,
    required this.sharpen,
    required this.skinPreserveDetail,
    required this.halation,
    required this.rgbSplit,
  });

  @override
  int get hashCode =>
      glow.hashCode ^
      grain.hashCode ^
      sharpen.hashCode ^
      skinPreserveDetail.hashCode ^
      halation.hashCode ^
      rgbSplit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwipeLookExtrasDto &&
          runtimeType == other.runtimeType &&
          glow == other.glow &&
          grain == other.grain &&
          sharpen == other.sharpen &&
          skinPreserveDetail == other.skinPreserveDetail &&
          halation == other.halation &&
          rgbSplit == other.rgbSplit;
}

/// TikTok / Instagram combo swipe looks (requires image_forge for implementation).
enum SwipeLookPreset {
  cleanGirlGlow,
  cloudSkin,
  goldenAura,
  softFocus,
  fauxFilm,
  boldGlamourLite,
  neonNight,
  animeAirbrush,
}

/// Text overlay drawing settings.
class TextOverlay {
  final String text;
  final int x;
  final int y;
  final double fontSize;
  final int colorR;
  final int colorG;
  final int colorB;
  final int colorA;

  const TextOverlay({
    required this.text,
    required this.x,
    required this.y,
    required this.fontSize,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      x.hashCode ^
      y.hashCode ^
      fontSize.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextOverlay &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          x == other.x &&
          y == other.y &&
          fontSize == other.fontSize &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA;
}
