// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audio_stream_format`, `begin_open`, `build_stream_table`, `byte_size`, `ffmpeg_version_string`, `find_best_audio_stream`, `from_internal`, `hw_decode_enabled`, `is_full_locked`, `log_decode_capabilities`, `metadata_complete`, `notify_frame_ready`, `notify_ready`, `open_audio_decoder`, `open_common`, `open_input_with_fast_fallback`, `probe_decode_capabilities_inner`, `pts_ms_opt`, `release_media_video_frame_pixel_buffer`, `start_subtitle_worker`, `stop_demuxer_session`, `stop_subtitle_worker`, `stop`, `strip_ass_overrides`, `subtitle_text`, `to_internal`, `update_time_internal`, `video_decoder_label`, `video_frame_queue_capacity_sw`, `video_frame_queue_capacity`, `video_stream_dims`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioPlayerState`, `DecoderRecoveryState`, `ExternalSubtitleSession`, `FrameQueue`, `OverlayAudioState`, `OverlayAudioTrack`, `PacketQueueInner`, `PlaybackClockInner`, `PlaybackSession`, `SendSafeStream`, `SubtitleCue`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_wire_name`, `is_cancelled`, `new`, `new`, `present_frame`, `present_frame`, `pts_ms`, `pts_ms`, `set_audio_clock`, `set_frame_ready`, `set_notify`, `wire_name`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `dequeue_best_for_time`, `dequeue`, `enqueue_video`, `enqueue`, `flush_video`, `flush`, `frame_memory_bytes`, `is_empty`, `latest_pts`, `len`, `max_size`, `new`, `open`, `overflow_count`, `set_volume`, `stop`, `volume_f32`

/// Probe linked FFmpeg once (safe to call from Dart at startup).
Future<DecodeCapabilities> probeDecodeCapabilities() =>
    RustLib.instance.api.crateApiRuntimeProbeDecodeCapabilities();

Future<void> ensureFfmpegInitialized() =>
    RustLib.instance.api.crateApiRuntimeEnsureFfmpegInitialized();

Future<PixelBufferHandoff?> mediaVideoFrameIntoPixelBufferHandoff({
  required MediaVideoFrame frame,
}) => RustLib.instance.api.crateApiRuntimeMediaVideoFrameIntoPixelBufferHandoff(
  frame: frame,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioRuntime>>
abstract class AudioRuntime implements RustOpaqueInterface {
  /// Add an overlay audio track. Returns the overlay ID.
  /// The track is demuxed and decoded in background threads, and its PCM
  /// output is mixed into the cpal callback alongside the source audio.
  Future<BigInt> addOverlay({
    required String path,
    required double volume,
    required BigInt timelineStartMs,
    required BigInt durationMs,
    required BigInt sourceStartMs,
  });

  /// Clear the trim-end flag (e.g. after a seek backward past trim end).
  Future<void> clearTrimEndReached();

  /// Flush all overlay frame queues (called on seek).
  Future<void> flushOverlayQueues();

  /// Current master gain 0.0..=1.0.
  Future<double> getVolume();

  /// Returns true when the audio clock has reached the trim end point.
  Future<bool> isTrimEndReached();

  /// Remove an overlay audio track by ID.
  Future<void> removeOverlay({required BigInt id});

  /// Enable or disable audio muting. When muted, the cpal callback writes
  /// silence while continuing to consume decoded frames so the clock and
  /// decoder pipeline stay in sync.
  Future<void> setMuted({required bool muted});

  /// Set volume for an overlay track (0.0 .. 1.0).
  Future<void> setOverlayVolume({required BigInt id, required double volume});

  /// Mute only the source (embedded video) audio lane. Overlay tracks keep playing.
  Future<void> setSourceMuted({required bool muted});

  /// Set the trim end point in ms. The cpal callback monitors the audio
  /// clock and sets `trim_end_reached` when it reaches this value.
  Future<void> setTrimEndMs({required BigInt endMs});

  /// Master output gain 0.0..=1.0 applied to source + overlay mix in the
  /// cpal callback. Independent from [`AudioRuntime::set_muted`].
  Future<void> setVolume({required double volume});

  Future<void> start();

  Future<void> stop();

  /// Stop and remove all overlay tracks.
  Future<void> stopAllOverlays();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GpuPresenter>>
abstract class GpuPresenter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<GpuPresenter> newInstance({required int textureId}) =>
      RustLib.instance.api.crateApiRuntimeGpuPresenterNew(textureId: textureId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaPlaybackEngine>>
abstract class MediaPlaybackEngine implements RustOpaqueInterface {
  /// Add an overlay audio track that will be mixed into playback in real-time.
  /// Returns the overlay ID (u64::MAX on error).
  Future<BigInt> addOverlayAudio({
    required String path,
    required double volume,
    required BigInt timelineStartMs,
    required BigInt durationMs,
    required BigInt sourceStartMs,
  });

  Future<BigInt> audioQueueBytes();

  Future<BigInt> audioQueueDurationMs();

  Future<BigInt> catchupDrops();

  Future<void> clearCancel();

  /// Stop and drop the external subtitle session (cues already ingested stay).
  Future<void> closeExternalSubtitle();

  /// Run the enhancement stage for one decoded frame.
  ///
  /// Returns a handoff for the enhanced surface, or `None` to present the
  /// decoded frame untouched. **Ownership:** on success the `+1` retain on
  /// `pixel_buffer_ptr` is consumed; on `None` the caller still owns it and
  /// must present that frame.
  Future<PixelBufferHandoff?> enhancePixelBuffer({
    required BigInt pixelBufferPtr,
    required int width,
    required int height,
    required BigInt ptsMs,
  });

  /// Retained decoded-frame memory in bytes (observable, §3/§16).
  Future<BigInt> frameMemoryBytes();

  /// Audio clock in ms (for Dart diagnostics / A/V drift display).
  /// Returns 0 until audio begins playing.
  Future<BigInt> getAudioClockMs();

  Future<BigInt> getAudioFrameQueueLen();

  Future<BigInt> getAudioPacketQueueLen();

  Future<Float32List> getAudioWaveform();

  /// Audio clock minus latest decoded video PTS (0 when in sync).
  Future<BigInt> getAvDriftMs();

  /// Phase 0: snapshot of linked FFmpeg / VideoToolbox decoder availability.
  Future<DecodeCapabilities> getDecodeCapabilities();

  /// Single-call diagnostics snapshot — replaces 11 individual FRB bridge
  /// calls with one, reducing per-tick overhead from ~22 calls/s to ~2.
  Future<DiagnosticsSnapshot> getDiagnostics();

  Future<BigInt> getDurationMs();

  Future<BigInt> getLastPresentedPtsMs();

  /// PTS of the newest decoded video frame still in the queue (0 if empty).
  Future<BigInt> getLatestDecodedVideoPtsMs();

  /// Master playback position in ms.
  ///
  /// Uses the sample-accurate **audio device clock** when audio is actively
  /// playing — this eliminates drift between the wall clock and the hardware
  /// audio output, which is the primary reason video lags behind audio.
  ///
  /// Falls back to the software wall clock during buffering, pause, and seek.
  Future<BigInt> getMediaTimeMs();

  Future<PlaybackState> getPlaybackState();

  Future<PlatformInt64> getSubtitleDelayMs();

  Future<BigInt> getTrimEndMs();

  Future<BigInt> getTrimStartMs();

  Future<BigInt> getVideoFrameQueueLen();

  Future<BigInt> getVideoPacketQueueLen();

  Future<double> getVolume();

  /// Wall-clock playback position (Instant-based), without audio preference.
  Future<BigInt> getWallClockMs();

  /// Audio-vs-presented drift (ms) that triggers automatic demuxer hard resync.
  Future<BigInt> hardResyncDriftThresholdMs();

  /// All streams discovered at open time (video/audio/subtitle).
  Future<List<MediaStreamInfo>> listStreams();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MediaPlaybackEngine> newInstance({
    required int textureId,
    required BigInt maxQueueSize,
    required int previewMaxEdge,
  }) => RustLib.instance.api.crateApiRuntimeMediaPlaybackEngineNew(
    textureId: textureId,
    maxQueueSize: maxQueueSize,
    previewMaxEdge: previewMaxEdge,
  );

  /// Open an external (sidecar) subtitle file or URL.
  ///
  /// Demuxed + decoded on its own thread into the shared cue queue, so it
  /// mixes with (or replaces) embedded cues. Times are used as-is plus
  /// [`MediaPlaybackEngine::set_subtitle_delay_ms`].
  Future<void> openExternalSubtitle({required String pathOrUrl});

  Future<void> openFile({required String path});

  /// Open an HTTP/HTTPS URL (streaming, HLS, localhost range servers).
  ///
  /// FFmpeg reads the URL directly — redirects, Range seeks, and HLS
  /// segment fetches all happen inside libavformat, so Dart never fetches
  /// bytes. Headers are forwarded as one `headers` dict entry
  /// (`"Name: Value\r\n"` per FFmpeg http conventions).
  Future<void> openUrl({required String url, required NetworkOptions options});

  Future<void> pause();

  /// Active cue text at `time_ms` (lines joined with `\n`), or None.
  ///
  /// Prunes cues long past their end time to bound memory.
  Future<String?> pollSubtitleText({required BigInt timeMs});

  /// Presenter tick interval in ms (~30 fps).
  Future<BigInt> presenterIntervalMs();

  Future<BigInt> probeDurationMs();

  Future<bool> pushAudioPacket({required MediaPacket packet});

  Future<bool> pushVideoPacket({required MediaPacket packet});

  /// Split drop counters (§6): overflow vs catch-up vs decoder.
  /// Empty polls are never counted — only actual discards.
  Future<BigInt> queueOverflowDrops();

  Future<BigInt> reconnectCount();

  /// Remove an overlay audio track by ID.
  Future<void> removeOverlayAudio({required BigInt id});

  /// Exact active rendering path (§8). Never claims zero-copy unless the
  /// VT IOSurface adoption path is actually active.
  Future<String> renderingPath();

  /// Request cancellation of blocked open/probe/network reads (§12).
  /// Tied to controller/source generation, seek replacement and disposal.
  Future<void> requestCancel();

  /// Resume a suspended session (§13).
  Future<void> resume();

  Future<void> seek({required BigInt timeMs});

  /// Switch the audio track during playback.
  ///
  /// Updates the decoder params, bumps the decoder epoch (the audio
  /// thread reopens its codec), and re-seeks to the current position so
  /// queues and clocks resync through the normal Flush machinery.
  Future<void> selectAudioStream({required int index});

  /// Select the embedded subtitle track (`-1` disables). Clears queued
  /// cues and re-seeks so the demuxer forwards the new stream.
  Future<void> selectSubtitleStream({required int index});

  /// Switch the video track during playback (params + re-seek; the video
  /// thread reopens its pipelines on the Flush sentinel).
  Future<void> selectVideoStream({required int index});

  Future<void> setMuted({required bool muted});

  /// Set volume for an overlay audio track (0.0 .. 1.0).
  Future<void> setOverlayVolume({required BigInt id, required double volume});

  Future<void> setRate({required double rate});

  /// Mute only embedded source audio during preview (overlay BGM keeps playing).
  Future<void> setSourceMuted({required bool muted});

  /// User subtitle delay in ms (signed; applied when cues are ingested).
  Future<void> setSubtitleDelayMs({required PlatformInt64 delayMs});

  /// Enable/disable cue delivery (decoding continues; polling returns None).
  Future<void> setSubtitlesEnabled({required bool enabled});

  /// Set the trim range in ms. Packets outside this range are skipped by
  /// the demuxer, and playback auto-pauses when reaching `end_ms`.
  Future<void> setTrimRange({required BigInt startMs, required BigInt endMs});

  /// Hard ceiling for the enhanced output longest edge (`0` = mode default).
  Future<void> setVideoEnhancementMaxOutputEdge({required int edge});

  /// Select an enhancement mode. Takes effect on the next presented frame:
  /// no media reopen, no decoder restart, no queue flush.
  ///
  /// Returns false when the device cannot run the requested mode (playback
  /// is unaffected — the normal render path stays in place).
  Future<bool> setVideoEnhancementMode({required VideoEnhancementMode mode});

  /// Display box in device pixels, used for the resolution-aware target.
  /// `(0, 0)` clears the hint.
  Future<void> setVideoEnhancementViewport({
    required int width,
    required int height,
  });

  /// Master output gain 0.0..=1.0 (source + overlays) in the cpal mixer.
  Future<void> setVolume({required double volume});

  Future<BigInt> staleDrops();

  Future<void> start();

  Future<void> stop();

  /// Lifecycle suspension (§13): park the presentation pump, audio device,
  /// diagnostics cadence and subtitle wakeups; retain the session for resume.
  /// No bridge frame calls are emitted while suspended.
  Future<void> suspend();

  Future<AudioFrame?> takeAudioFrame();

  /// Returns the frame selected by [`PresenterRuntime`] (frame-ready pump),
  /// not the raw decode queue. Counts bridge calls vs presented frames
  /// separately (§6): empty polls return None and are never drops.
  Future<MediaVideoFrame?> takeVideoFrame();

  /// What this device can do. Safe to call before any media is open.
  Future<VideoEnhancementCapabilities> videoEnhancementCapabilities();

  /// Current enhancement state for diagnostics.
  Future<VideoEnhancementStatus> videoEnhancementStatus();

  /// Compressed packet bytes currently buffered (video/audio).
  Future<BigInt> videoQueueBytes();

  Future<BigInt> videoQueueDurationMs();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PacketQueue>>
abstract class PacketQueue implements RustOpaqueInterface {
  /// Current buffered bytes (observable via diagnostics).
  Future<BigInt> bytes();

  Future<void> close();

  /// Current buffered span in ms (max PTS − min PTS, 0 when <2 timed packets).
  Future<BigInt> durationMs();

  Future<void> flush();

  Future<bool> isEmpty();

  Future<BigInt> len();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PacketQueue> newInstance({required BigInt maxSize}) =>
      RustLib.instance.api.crateApiRuntimePacketQueueNew(maxSize: maxSize);

  /// Budget-aware constructor: count AND bytes AND duration all bound.
  static Future<PacketQueue> newWithBudgets({
    required BigInt maxSize,
    required BigInt maxBytes,
    required BigInt maxDurationMs,
  }) => RustLib.instance.api.crateApiRuntimePacketQueueNewWithBudgets(
    maxSize: maxSize,
    maxBytes: maxBytes,
    maxDurationMs: maxDurationMs,
  );

  Future<QueuePacket?> pop();

  Future<bool> push({required QueuePacket packet});

  /// Non-blocking pop for frame-ready pump integration (returns None when
  /// empty instead of blocking). Used by interrupt-aware paths.
  Future<QueuePacket?> tryPop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaybackClock>>
abstract class PlaybackClock implements RustOpaqueInterface {
  Future<void> advancePresentedPts({required BigInt ptsMs});

  /// Freeze media time during a transient video starvation. This is a
  /// state transition only: it deliberately does not seek, flush queues,
  /// reopen the source, or reset the last presented PTS.
  Future<void> enterRebuffering();

  Future<BigInt> getLastPresentedPtsMs();

  Future<BigInt> getMediaTimeMs();

  Future<PlaybackState> getState();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PlaybackClock> newInstance() =>
      RustLib.instance.api.crateApiRuntimePlaybackClockNew();

  Future<void> pause();

  /// Clears a stale presented PTS after backward seek (presented >> audio).
  Future<void> resetPresentedPtsForSeek({required BigInt toMs});

  /// Resume a previously starved session from the exact frozen media time.
  Future<void> resumeFromRebuffering();

  Future<void> seek({required BigInt timeMs});

  /// Called when the seek is complete — resumes the appropriate playback state and aligns clock to presented frame PTS.
  Future<void> seekComplete({
    required bool wasPlaying,
    required BigInt presentedPtsMs,
  });

  Future<void> setRate({required double rate});

  Future<void> start();

  /// Keep the wall clock aligned with the audio sample clock during playback.
  Future<void> syncFromAudioMs({required BigInt audioMs});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QueuePacket>>
abstract class QueuePacket implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VideoRuntime>>
abstract class VideoRuntime implements RustOpaqueInterface {
  Future<void> start();

  Future<void> stop();
}

abstract class HasPts {
  Future<BigInt> ptsMs();
}

/// Decoded audio frame (stereo PCM f32 samples).
class AudioFrame {
  final BigInt ptsMs;
  final int sampleRate;
  final int channels;
  final Float32List samples;
  final BigInt seekGeneration;

  const AudioFrame({
    required this.ptsMs,
    required this.sampleRate,
    required this.channels,
    required this.samples,
    required this.seekGeneration,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      samples.hashCode ^
      seekGeneration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFrame &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          samples == other.samples &&
          seekGeneration == other.seekGeneration;
}

/// Phase 0 diagnostic: which decoders exist in the **linked** FFmpeg build.
class DecodeCapabilities {
  /// HEVC + VideoToolbox hwaccel available in linked FFmpeg.
  final bool hevcVideotoolbox;

  /// H.264 + VideoToolbox hwaccel available in linked FFmpeg.
  final bool h264Videotoolbox;

  /// True when `VFP_DISABLE_HW_DECODE` is set.
  final bool hwDecodeDisabledEnv;

  /// libavutil version string (e.g. `59.39.100`).
  final String ffmpegVersion;

  /// Human-readable readiness for 4K iPhone HEVC preview.
  final bool readyForHevcHw;

  /// Hint when HW decoders are missing from the dylib FFmpeg.
  final String hint;

  const DecodeCapabilities({
    required this.hevcVideotoolbox,
    required this.h264Videotoolbox,
    required this.hwDecodeDisabledEnv,
    required this.ffmpegVersion,
    required this.readyForHevcHw,
    required this.hint,
  });

  @override
  int get hashCode =>
      hevcVideotoolbox.hashCode ^
      h264Videotoolbox.hashCode ^
      hwDecodeDisabledEnv.hashCode ^
      ffmpegVersion.hashCode ^
      readyForHevcHw.hashCode ^
      hint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodeCapabilities &&
          runtimeType == other.runtimeType &&
          hevcVideotoolbox == other.hevcVideotoolbox &&
          h264Videotoolbox == other.h264Videotoolbox &&
          hwDecodeDisabledEnv == other.hwDecodeDisabledEnv &&
          ffmpegVersion == other.ffmpegVersion &&
          readyForHevcHw == other.readyForHevcHw &&
          hint == other.hint;
}

/// All playback diagnostics in one struct — returned by [`MediaPlaybackEngine::get_diagnostics`].
class DiagnosticsSnapshot {
  final PlaybackState state;
  final BigInt mediaTimeMs;
  final BigInt audioClockMs;
  final BigInt wallClockMs;
  final BigInt latestDecodedPtsMs;
  final BigInt presentedPtsMs;
  final BigInt avDriftMs;
  final BigInt videoPacketsInQueue;
  final BigInt audioPacketsInQueue;
  final BigInt videoFramesInQueue;
  final BigInt audioFramesInQueue;

  /// Container bytes demuxed since open.
  final BigInt bytesRead;

  /// Demuxed-bytes read bitrate estimate (bits/s, 0 until 500 ms elapsed).
  final BigInt readBitrateBps;

  /// Decoded-ahead-of-presentation buffer (latest decoded − presented).
  final BigInt bufferedDurationMs;

  /// Pre-decode video drops (stale generation + catch-up policy).
  final BigInt droppedVideoFrames;

  /// e.g. `hevc-videotoolbox`, `h264-software`, `none` before first open.
  final String activeVideoDecoder;

  /// True when the active video pipeline is hardware decode.
  final bool hwDecodeActive;

  /// Cues currently held for polling.
  final BigInt subtitleCuesPending;

  /// Selected stream indices (−1 = none/off).
  final int selectedVideoIndex;
  final int selectedAudioIndex;
  final int selectedSubtitleIndex;

  const DiagnosticsSnapshot({
    required this.state,
    required this.mediaTimeMs,
    required this.audioClockMs,
    required this.wallClockMs,
    required this.latestDecodedPtsMs,
    required this.presentedPtsMs,
    required this.avDriftMs,
    required this.videoPacketsInQueue,
    required this.audioPacketsInQueue,
    required this.videoFramesInQueue,
    required this.audioFramesInQueue,
    required this.bytesRead,
    required this.readBitrateBps,
    required this.bufferedDurationMs,
    required this.droppedVideoFrames,
    required this.activeVideoDecoder,
    required this.hwDecodeActive,
    required this.subtitleCuesPending,
    required this.selectedVideoIndex,
    required this.selectedAudioIndex,
    required this.selectedSubtitleIndex,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      mediaTimeMs.hashCode ^
      audioClockMs.hashCode ^
      wallClockMs.hashCode ^
      latestDecodedPtsMs.hashCode ^
      presentedPtsMs.hashCode ^
      avDriftMs.hashCode ^
      videoPacketsInQueue.hashCode ^
      audioPacketsInQueue.hashCode ^
      videoFramesInQueue.hashCode ^
      audioFramesInQueue.hashCode ^
      bytesRead.hashCode ^
      readBitrateBps.hashCode ^
      bufferedDurationMs.hashCode ^
      droppedVideoFrames.hashCode ^
      activeVideoDecoder.hashCode ^
      hwDecodeActive.hashCode ^
      subtitleCuesPending.hashCode ^
      selectedVideoIndex.hashCode ^
      selectedAudioIndex.hashCode ^
      selectedSubtitleIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticsSnapshot &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          mediaTimeMs == other.mediaTimeMs &&
          audioClockMs == other.audioClockMs &&
          wallClockMs == other.wallClockMs &&
          latestDecodedPtsMs == other.latestDecodedPtsMs &&
          presentedPtsMs == other.presentedPtsMs &&
          avDriftMs == other.avDriftMs &&
          videoPacketsInQueue == other.videoPacketsInQueue &&
          audioPacketsInQueue == other.audioPacketsInQueue &&
          videoFramesInQueue == other.videoFramesInQueue &&
          audioFramesInQueue == other.audioFramesInQueue &&
          bytesRead == other.bytesRead &&
          readBitrateBps == other.readBitrateBps &&
          bufferedDurationMs == other.bufferedDurationMs &&
          droppedVideoFrames == other.droppedVideoFrames &&
          activeVideoDecoder == other.activeVideoDecoder &&
          hwDecodeActive == other.hwDecodeActive &&
          subtitleCuesPending == other.subtitleCuesPending &&
          selectedVideoIndex == other.selectedVideoIndex &&
          selectedAudioIndex == other.selectedAudioIndex &&
          selectedSubtitleIndex == other.selectedSubtitleIndex;
}

/// A simplified demuxed media packet.
class MediaPacket {
  final BigInt ptsMs;
  final BigInt dtsMs;
  final BigInt streamIndex;
  final bool isKeyframe;
  final Uint8List data;

  const MediaPacket({
    required this.ptsMs,
    required this.dtsMs,
    required this.streamIndex,
    required this.isKeyframe,
    required this.data,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      dtsMs.hashCode ^
      streamIndex.hashCode ^
      isKeyframe.hashCode ^
      data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaPacket &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          dtsMs == other.dtsMs &&
          streamIndex == other.streamIndex &&
          isKeyframe == other.isKeyframe &&
          data == other.data;
}

/// One stream discovered in the opened container or network input.
///
/// Built by [`MediaPlaybackEngine::list_streams`] from FFmpeg stream
/// parameters + metadata (language/title) + disposition (default/forced).
class MediaStreamInfo {
  /// FFmpeg stream index (stable for the open session).
  final int index;
  final StreamKind kind;
  final String codecName;
  final String language;
  final String title;

  /// Bits per second (0 when the container does not report it).
  final BigInt bitrate;

  /// Video dimensions (0 for non-video).
  final int width;
  final int height;

  /// Audio channels / sample rate (0 for non-audio).
  final int channels;
  final int sampleRate;
  final bool isDefault;
  final bool isForced;

  const MediaStreamInfo({
    required this.index,
    required this.kind,
    required this.codecName,
    required this.language,
    required this.title,
    required this.bitrate,
    required this.width,
    required this.height,
    required this.channels,
    required this.sampleRate,
    required this.isDefault,
    required this.isForced,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      kind.hashCode ^
      codecName.hashCode ^
      language.hashCode ^
      title.hashCode ^
      bitrate.hashCode ^
      width.hashCode ^
      height.hashCode ^
      channels.hashCode ^
      sampleRate.hashCode ^
      isDefault.hashCode ^
      isForced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaStreamInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          kind == other.kind &&
          codecName == other.codecName &&
          language == other.language &&
          title == other.title &&
          bitrate == other.bitrate &&
          width == other.width &&
          height == other.height &&
          channels == other.channels &&
          sampleRate == other.sampleRate &&
          isDefault == other.isDefault &&
          isForced == other.isForced;
}

/// Decoded video frame for presentation.
///
/// **RGBA path:** [pixels] is `width × height × 4`, [pixel_buffer_ptr] is 0.
/// **Apple HW path:** [pixel_buffer_ptr] is a retained BGRA `CVPixelBuffer*`; [pixels] is empty.
class MediaVideoFrame {
  final BigInt ptsMs;
  final int width;
  final int height;
  final Uint8List pixels;
  final BigInt pixelBufferPtr;
  final BigInt seekGeneration;

  const MediaVideoFrame({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.pixels,
    required this.pixelBufferPtr,
    required this.seekGeneration,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixels.hashCode ^
      pixelBufferPtr.hashCode ^
      seekGeneration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaVideoFrame &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels &&
          pixelBufferPtr == other.pixelBufferPtr &&
          seekGeneration == other.seekGeneration;
}

/// HTTP(S) open options for [`MediaPlaybackEngine::open_url`].
///
/// FFmpeg reads the URL directly (redirects + Range seeks included), so
/// Dart never fetches bytes. Headers use exact `Name: Value` pairs.
class NetworkOptions {
  /// Extra HTTP headers (e.g. `Authorization`, `Cookie`).
  final Map<String, String> headers;

  /// `User-Agent` override ("" = FFmpeg default).
  final String userAgent;

  /// Read timeout in ms (0 = FFmpeg default).
  final BigInt timeoutMs;

  /// Enable `reconnect`/`reconnect_streamed` for flaky links (HLS/live).
  final bool reconnect;

  const NetworkOptions({
    required this.headers,
    required this.userAgent,
    required this.timeoutMs,
    required this.reconnect,
  });

  static Future<NetworkOptions> default_() =>
      RustLib.instance.api.crateApiRuntimeNetworkOptionsDefault();

  @override
  int get hashCode =>
      headers.hashCode ^
      userAgent.hashCode ^
      timeoutMs.hashCode ^
      reconnect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkOptions &&
          runtimeType == other.runtimeType &&
          headers == other.headers &&
          userAgent == other.userAgent &&
          timeoutMs == other.timeoutMs &&
          reconnect == other.reconnect;
}

/// Hand off `CVPixelBuffer` to Flutter without releasing on [MediaVideoFrame] drop.
class PixelBufferHandoff {
  final BigInt ptsMs;
  final int width;
  final int height;
  final BigInt pixelBufferPtr;
  final BigInt seekGeneration;

  const PixelBufferHandoff({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.pixelBufferPtr,
    required this.seekGeneration,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixelBufferPtr.hashCode ^
      seekGeneration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PixelBufferHandoff &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          pixelBufferPtr == other.pixelBufferPtr &&
          seekGeneration == other.seekGeneration;
}

/// State of the playback clock.
enum PlaybackState {
  idle,
  playing,
  paused,
  seeking,
  ended,

  /// Playback is temporarily starved of presentable video frames. The
  /// demux/decode session stays open; the clock and audio output are held
  /// until the recovery buffer is ready.
  rebuffering,
}

/// Kind of a container stream discovered at open time.
enum StreamKind { video, audio, subtitle }

/// What this device/build can do. Never fails playback: `supported == false`
/// simply means the normal render path stays in place.
class VideoEnhancementCapabilities {
  final bool supported;

  /// Backend identity, e.g. `metal_wgpu`.
  final String backend;

  /// Modes that will actually run (always contains `Off`).
  final List<VideoEnhancementMode> modes;

  /// Largest output longest edge the backend produces.
  final int maxOutputEdge;

  /// Why enhancement is unavailable (empty when supported).
  final String reason;

  const VideoEnhancementCapabilities({
    required this.supported,
    required this.backend,
    required this.modes,
    required this.maxOutputEdge,
    required this.reason,
  });

  @override
  int get hashCode =>
      supported.hashCode ^
      backend.hashCode ^
      modes.hashCode ^
      maxOutputEdge.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoEnhancementCapabilities &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          backend == other.backend &&
          modes == other.modes &&
          maxOutputEdge == other.maxOutputEdge &&
          reason == other.reason;
}

/// Requested video enhancement quality.
enum VideoEnhancementMode {
  /// Untouched render path (default).
  off,

  /// Lightweight GPU sharpen at native size.
  sharp,

  /// High-quality upscale + adaptive sharpen + light dither.
  enhanced,

  /// Best non-AI upscale (separable Lanczos-3) + adaptive sharpen.
  highQuality,
}

/// Live enhancement state for diagnostics.
class VideoEnhancementStatus {
  final bool supported;
  final VideoEnhancementMode requestedMode;

  /// Mode actually running; differs from `requested_mode` after an
  /// automatic quality downgrade.
  final VideoEnhancementMode activeMode;
  final String backend;

  /// Executed pass path, e.g. `metal_lanczos_cas`.
  final String path;

  /// `none` / `catmull_rom` / `lanczos3`.
  final String scaler;
  final int inputWidth;
  final int inputHeight;
  final int outputWidth;
  final int outputHeight;

  /// Enhancement stage time for the last frame (ms).
  final double lastFrameMs;

  /// Smoothed enhancement stage time (ms).
  final double averageFrameMs;

  /// Source frame interval the stage is measured against (ms).
  final double deadlineMs;
  final BigInt deadlineMisses;
  final BigInt hardDeadlineMisses;
  final BigInt enhancedFrames;
  final BigInt bypassedFrames;
  final BigInt failedFrames;

  /// GPU passes issued for the last frame.
  final int passes;

  /// Why enhancement fell back (empty when healthy).
  final String fallbackReason;

  /// Why the last frame was bypassed (empty when it was enhanced).
  final String bypassReason;

  const VideoEnhancementStatus({
    required this.supported,
    required this.requestedMode,
    required this.activeMode,
    required this.backend,
    required this.path,
    required this.scaler,
    required this.inputWidth,
    required this.inputHeight,
    required this.outputWidth,
    required this.outputHeight,
    required this.lastFrameMs,
    required this.averageFrameMs,
    required this.deadlineMs,
    required this.deadlineMisses,
    required this.hardDeadlineMisses,
    required this.enhancedFrames,
    required this.bypassedFrames,
    required this.failedFrames,
    required this.passes,
    required this.fallbackReason,
    required this.bypassReason,
  });

  @override
  int get hashCode =>
      supported.hashCode ^
      requestedMode.hashCode ^
      activeMode.hashCode ^
      backend.hashCode ^
      path.hashCode ^
      scaler.hashCode ^
      inputWidth.hashCode ^
      inputHeight.hashCode ^
      outputWidth.hashCode ^
      outputHeight.hashCode ^
      lastFrameMs.hashCode ^
      averageFrameMs.hashCode ^
      deadlineMs.hashCode ^
      deadlineMisses.hashCode ^
      hardDeadlineMisses.hashCode ^
      enhancedFrames.hashCode ^
      bypassedFrames.hashCode ^
      failedFrames.hashCode ^
      passes.hashCode ^
      fallbackReason.hashCode ^
      bypassReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoEnhancementStatus &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          requestedMode == other.requestedMode &&
          activeMode == other.activeMode &&
          backend == other.backend &&
          path == other.path &&
          scaler == other.scaler &&
          inputWidth == other.inputWidth &&
          inputHeight == other.inputHeight &&
          outputWidth == other.outputWidth &&
          outputHeight == other.outputHeight &&
          lastFrameMs == other.lastFrameMs &&
          averageFrameMs == other.averageFrameMs &&
          deadlineMs == other.deadlineMs &&
          deadlineMisses == other.deadlineMisses &&
          hardDeadlineMisses == other.hardDeadlineMisses &&
          enhancedFrames == other.enhancedFrames &&
          bypassedFrames == other.bypassedFrames &&
          failedFrames == other.failedFrames &&
          passes == other.passes &&
          fallbackReason == other.fallbackReason &&
          bypassReason == other.bypassReason;
}
