// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1463065212;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__active_job_count_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "active_job_count",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::active_job_count())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__batch_thumbnail_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "batch_thumbnail_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_options =
                <crate::types::BatchThumbnailBytesOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::batch_thumbnail_bytes(api_options).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__batch_thumbnails_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "batch_thumbnails",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_options = <crate::types::BatchThumbnailOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::batch_thumbnails(api_options).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__cancel_job_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_job",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_job_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::cancel_job(api_job_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__cleanup_job_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cleanup_job",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_job_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::cleanup_job(api_job_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__decode_preview_frame_pixel_buffer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decode_preview_frame_pixel_buffer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input_path = <String>::sse_decode(&mut deserializer);
            let api_position_ms = <u64>::sse_decode(&mut deserializer);
            let api_max_edge = <Option<u32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::decode_preview_frame_pixel_buffer(
                            api_input_path,
                            api_position_ms,
                            api_max_edge,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__decode_preview_frame_rgba_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decode_preview_frame_rgba",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input_path = <String>::sse_decode(&mut deserializer);
            let api_position_ms = <u64>::sse_decode(&mut deserializer);
            let api_max_edge = <Option<u32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::decode_preview_frame_rgba(
                            api_input_path,
                            api_position_ms,
                            api_max_edge,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__get_media_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_media_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::get_media_info(api_path)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__initialize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::initialize()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__prefetch_remote_input_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prefetch_remote_input",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_url = <String>::sse_decode(&mut deserializer);
            let api_dest_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::prefetch_remote_input(api_url, api_dest_dir)?;
                    Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__release_preview_pixel_buffer_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "release_preview_pixel_buffer",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_pixel_buffer_ptr = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::release_preview_pixel_buffer(api_pixel_buffer_ptr);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__start_compress_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_compress",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_options = <crate::types::CompressOptions>::sse_decode(&mut deserializer);
            let api_progress = <StreamSink<
                crate::types::ProgressEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::start_compress(api_options, api_progress).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__thumbnail_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thumbnail",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_options = <crate::types::ThumbnailOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::thumbnail(api_options).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__thumbnail_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thumbnail_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_options = <crate::types::ThumbnailBytesOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::thumbnail_bytes(api_options).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__error__video_processor_error_error_code_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "video_processor_error_error_code",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::error::VideoProcessorError>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::error::VideoProcessorError::error_code(&api_that),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__error__video_processor_error_error_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "video_processor_error_error_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::error::VideoProcessorError>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::error::VideoProcessorError::error_message(&api_that),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__wait_for_job_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "wait_for_job",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_job_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::wait_for_job(api_job_id).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::types::ProgressEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::types::BatchThumbnailBytesOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_positionsMs = <Vec<u64>>::sse_decode(deserializer);
        let mut var_width = <Option<u32>>::sse_decode(deserializer);
        let mut var_height = <Option<u32>>::sse_decode(deserializer);
        let mut var_format = <crate::types::ThumbnailFormat>::sse_decode(deserializer);
        return crate::types::BatchThumbnailBytesOptions {
            input_path: var_inputPath,
            positions_ms: var_positionsMs,
            width: var_width,
            height: var_height,
            format: var_format,
        };
    }
}

impl SseDecode for crate::types::BatchThumbnailBytesResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_frames = <Vec<Vec<u8>>>::sse_decode(deserializer);
        return crate::types::BatchThumbnailBytesResult { frames: var_frames };
    }
}

impl SseDecode for crate::types::BatchThumbnailOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_outputPaths = <Option<Vec<String>>>::sse_decode(deserializer);
        let mut var_positionsMs = <Vec<u64>>::sse_decode(deserializer);
        let mut var_width = <Option<u32>>::sse_decode(deserializer);
        let mut var_height = <Option<u32>>::sse_decode(deserializer);
        let mut var_format = <crate::types::ThumbnailFormat>::sse_decode(deserializer);
        return crate::types::BatchThumbnailOptions {
            input_path: var_inputPath,
            output_dir: var_outputDir,
            output_paths: var_outputPaths,
            positions_ms: var_positionsMs,
            width: var_width,
            height: var_height,
            format: var_format,
        };
    }
}

impl SseDecode for crate::types::BatchThumbnailResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_paths = <Vec<String>>::sse_decode(deserializer);
        return crate::types::BatchThumbnailResult { paths: var_paths };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::types::CompressOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <Option<String>>::sse_decode(deserializer);
        let mut var_quality = <crate::types::VideoQuality>::sse_decode(deserializer);
        let mut var_codec = <crate::types::VideoCodec>::sse_decode(deserializer);
        let mut var_crf = <Option<u8>>::sse_decode(deserializer);
        let mut var_targetBitrate = <Option<u64>>::sse_decode(deserializer);
        let mut var_maxWidth = <Option<u32>>::sse_decode(deserializer);
        let mut var_maxHeight = <Option<u32>>::sse_decode(deserializer);
        let mut var_maxFps = <Option<f32>>::sse_decode(deserializer);
        let mut var_includeAudio = <bool>::sse_decode(deserializer);
        let mut var_fastStart = <bool>::sse_decode(deserializer);
        let mut var_fragmentedMp4 = <bool>::sse_decode(deserializer);
        let mut var_preferHardwareEncoder = <bool>::sse_decode(deserializer);
        let mut var_startMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_endMs = <Option<u64>>::sse_decode(deserializer);
        return crate::types::CompressOptions {
            input_path: var_inputPath,
            output_path: var_outputPath,
            quality: var_quality,
            codec: var_codec,
            crf: var_crf,
            target_bitrate: var_targetBitrate,
            max_width: var_maxWidth,
            max_height: var_maxHeight,
            max_fps: var_maxFps,
            include_audio: var_includeAudio,
            fast_start: var_fastStart,
            fragmented_mp4: var_fragmentedMp4,
            prefer_hardware_encoder: var_preferHardwareEncoder,
            start_ms: var_startMs,
            end_ms: var_endMs,
        };
    }
}

impl SseDecode for crate::types::CompressResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_durationMs = <u64>::sse_decode(deserializer);
        let mut var_fileSize = <u64>::sse_decode(deserializer);
        let mut var_usedHardwareAcceleration = <bool>::sse_decode(deserializer);
        let mut var_encoderName = <String>::sse_decode(deserializer);
        let mut var_pipelineMode = <String>::sse_decode(deserializer);
        return crate::types::CompressResult {
            output_path: var_outputPath,
            duration_ms: var_durationMs,
            file_size: var_fileSize,
            used_hardware_acceleration: var_usedHardwareAcceleration,
            encoder_name: var_encoderName,
            pipeline_mode: var_pipelineMode,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::types::JobResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <crate::types::CompressResult>::sse_decode(deserializer);
                return crate::types::JobResult::Compress(var_field0);
            }
            1 => {
                return crate::types::JobResult::Empty;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<Vec<u8>>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::types::MediaInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_durationMs = <u64>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_rotation = <i32>::sse_decode(deserializer);
        let mut var_fps = <f32>::sse_decode(deserializer);
        let mut var_videoCodec = <String>::sse_decode(deserializer);
        let mut var_audioCodec = <Option<String>>::sse_decode(deserializer);
        let mut var_bitrate = <u64>::sse_decode(deserializer);
        let mut var_fileSize = <u64>::sse_decode(deserializer);
        return crate::types::MediaInfo {
            duration_ms: var_durationMs,
            width: var_width,
            height: var_height,
            rotation: var_rotation,
            fps: var_fps,
            video_codec: var_videoCodec,
            audio_codec: var_audioCodec,
            bitrate: var_bitrate,
            file_size: var_fileSize,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<String>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::types::PreviewFramePixelBuffer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ptsMs = <u64>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_pixelBufferPtr = <u64>::sse_decode(deserializer);
        return crate::types::PreviewFramePixelBuffer {
            pts_ms: var_ptsMs,
            width: var_width,
            height: var_height,
            pixel_buffer_ptr: var_pixelBufferPtr,
        };
    }
}

impl SseDecode for crate::types::PreviewFrameRgba {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ptsMs = <u64>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_rgba = <Vec<u8>>::sse_decode(deserializer);
        return crate::types::PreviewFrameRgba {
            pts_ms: var_ptsMs,
            width: var_width,
            height: var_height,
            rgba: var_rgba,
        };
    }
}

impl SseDecode for crate::types::ProcessingPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::types::ProcessingPhase::Probing,
            1 => crate::types::ProcessingPhase::Decoding,
            2 => crate::types::ProcessingPhase::Encoding,
            3 => crate::types::ProcessingPhase::Muxing,
            4 => crate::types::ProcessingPhase::Thumbnail,
            5 => crate::types::ProcessingPhase::Done,
            6 => crate::types::ProcessingPhase::Cancelled,
            7 => crate::types::ProcessingPhase::Failed,
            _ => unreachable!("Invalid variant for ProcessingPhase: {}", inner),
        };
    }
}

impl SseDecode for crate::types::ProgressEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_jobId = <String>::sse_decode(deserializer);
        let mut var_phase = <crate::types::ProcessingPhase>::sse_decode(deserializer);
        let mut var_percent = <f32>::sse_decode(deserializer);
        let mut var_frame = <u64>::sse_decode(deserializer);
        let mut var_fps = <f32>::sse_decode(deserializer);
        let mut var_etaMs = <u64>::sse_decode(deserializer);
        return crate::types::ProgressEvent {
            job_id: var_jobId,
            phase: var_phase,
            percent: var_percent,
            frame: var_frame,
            fps: var_fps,
            eta_ms: var_etaMs,
        };
    }
}

impl SseDecode for crate::types::ThumbnailBytesOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_positionMs = <u64>::sse_decode(deserializer);
        let mut var_width = <Option<u32>>::sse_decode(deserializer);
        let mut var_height = <Option<u32>>::sse_decode(deserializer);
        let mut var_format = <crate::types::ThumbnailFormat>::sse_decode(deserializer);
        return crate::types::ThumbnailBytesOptions {
            input_path: var_inputPath,
            position_ms: var_positionMs,
            width: var_width,
            height: var_height,
            format: var_format,
        };
    }
}

impl SseDecode for crate::types::ThumbnailFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::types::ThumbnailFormat::Jpeg,
            1 => crate::types::ThumbnailFormat::Webp,
            _ => unreachable!("Invalid variant for ThumbnailFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::types::ThumbnailOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <Option<String>>::sse_decode(deserializer);
        let mut var_positionMs = <u64>::sse_decode(deserializer);
        let mut var_width = <Option<u32>>::sse_decode(deserializer);
        let mut var_height = <Option<u32>>::sse_decode(deserializer);
        let mut var_format = <crate::types::ThumbnailFormat>::sse_decode(deserializer);
        return crate::types::ThumbnailOptions {
            input_path: var_inputPath,
            output_path: var_outputPath,
            position_ms: var_positionMs,
            width: var_width,
            height: var_height,
            format: var_format,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::types::VideoCodec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::types::VideoCodec::H264,
            1 => crate::types::VideoCodec::Hevc,
            _ => unreachable!("Invalid variant for VideoCodec: {}", inner),
        };
    }
}

impl SseDecode for crate::error::VideoProcessorError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::InvalidInput(var_field0);
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::FileNotFound(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::UnsupportedCodec(var_field0);
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::JobNotFound(var_field0);
            }
            4 => {
                return crate::error::VideoProcessorError::Cancelled;
            }
            5 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::IoError(var_field0);
            }
            6 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::FfmpegError(var_field0);
            }
            7 => {
                return crate::error::VideoProcessorError::QueueFull;
            }
            8 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::VideoProcessorError::Internal(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::types::VideoQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::types::VideoQuality::Low,
            1 => crate::types::VideoQuality::Medium,
            2 => crate::types::VideoQuality::High,
            3 => crate::types::VideoQuality::Custom,
            4 => crate::types::VideoQuality::Instagram,
            5 => crate::types::VideoQuality::Whatsapp,
            6 => crate::types::VideoQuality::Telegram,
            7 => crate::types::VideoQuality::Youtube,
            8 => crate::types::VideoQuality::Lossless,
            _ => unreachable!("Invalid variant for VideoQuality: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__active_job_count_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__batch_thumbnail_bytes_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__batch_thumbnails_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__cancel_job_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__cleanup_job_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__decode_preview_frame_pixel_buffer_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__decode_preview_frame_rgba_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__get_media_info_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__initialize_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__start_compress_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__thumbnail_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__thumbnail_bytes_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__error__video_processor_error_error_code_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        17 => wire__crate__error__video_processor_error_error_message_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        18 => wire__crate__api__wait_for_job_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        11 => wire__crate__api__prefetch_remote_input_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__release_preview_pixel_buffer_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::BatchThumbnailBytesOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.positions_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::BatchThumbnailBytesOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::BatchThumbnailBytesOptions>
    for crate::types::BatchThumbnailBytesOptions
{
    fn into_into_dart(self) -> crate::types::BatchThumbnailBytesOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::BatchThumbnailBytesResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.frames.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::BatchThumbnailBytesResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::BatchThumbnailBytesResult>
    for crate::types::BatchThumbnailBytesResult
{
    fn into_into_dart(self) -> crate::types::BatchThumbnailBytesResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::BatchThumbnailOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.output_paths.into_into_dart().into_dart(),
            self.positions_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::BatchThumbnailOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::BatchThumbnailOptions>
    for crate::types::BatchThumbnailOptions
{
    fn into_into_dart(self) -> crate::types::BatchThumbnailOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::BatchThumbnailResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.paths.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::BatchThumbnailResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::BatchThumbnailResult>
    for crate::types::BatchThumbnailResult
{
    fn into_into_dart(self) -> crate::types::BatchThumbnailResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::CompressOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.codec.into_into_dart().into_dart(),
            self.crf.into_into_dart().into_dart(),
            self.target_bitrate.into_into_dart().into_dart(),
            self.max_width.into_into_dart().into_dart(),
            self.max_height.into_into_dart().into_dart(),
            self.max_fps.into_into_dart().into_dart(),
            self.include_audio.into_into_dart().into_dart(),
            self.fast_start.into_into_dart().into_dart(),
            self.fragmented_mp4.into_into_dart().into_dart(),
            self.prefer_hardware_encoder.into_into_dart().into_dart(),
            self.start_ms.into_into_dart().into_dart(),
            self.end_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::CompressOptions {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::CompressOptions>
    for crate::types::CompressOptions
{
    fn into_into_dart(self) -> crate::types::CompressOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::CompressResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.file_size.into_into_dart().into_dart(),
            self.used_hardware_acceleration.into_into_dart().into_dart(),
            self.encoder_name.into_into_dart().into_dart(),
            self.pipeline_mode.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::CompressResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::CompressResult>
    for crate::types::CompressResult
{
    fn into_into_dart(self) -> crate::types::CompressResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::JobResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::types::JobResult::Compress(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::types::JobResult::Empty => [1.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::JobResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::JobResult> for crate::types::JobResult {
    fn into_into_dart(self) -> crate::types::JobResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::MediaInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.duration_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.rotation.into_into_dart().into_dart(),
            self.fps.into_into_dart().into_dart(),
            self.video_codec.into_into_dart().into_dart(),
            self.audio_codec.into_into_dart().into_dart(),
            self.bitrate.into_into_dart().into_dart(),
            self.file_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::MediaInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::MediaInfo> for crate::types::MediaInfo {
    fn into_into_dart(self) -> crate::types::MediaInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::PreviewFramePixelBuffer {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pts_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.pixel_buffer_ptr.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::PreviewFramePixelBuffer
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::PreviewFramePixelBuffer>
    for crate::types::PreviewFramePixelBuffer
{
    fn into_into_dart(self) -> crate::types::PreviewFramePixelBuffer {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::PreviewFrameRgba {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pts_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.rgba.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::PreviewFrameRgba
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::PreviewFrameRgba>
    for crate::types::PreviewFrameRgba
{
    fn into_into_dart(self) -> crate::types::PreviewFrameRgba {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::ProcessingPhase {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Probing => 0.into_dart(),
            Self::Decoding => 1.into_dart(),
            Self::Encoding => 2.into_dart(),
            Self::Muxing => 3.into_dart(),
            Self::Thumbnail => 4.into_dart(),
            Self::Done => 5.into_dart(),
            Self::Cancelled => 6.into_dart(),
            Self::Failed => 7.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::ProcessingPhase {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::ProcessingPhase>
    for crate::types::ProcessingPhase
{
    fn into_into_dart(self) -> crate::types::ProcessingPhase {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::ProgressEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.job_id.into_into_dart().into_dart(),
            self.phase.into_into_dart().into_dart(),
            self.percent.into_into_dart().into_dart(),
            self.frame.into_into_dart().into_dart(),
            self.fps.into_into_dart().into_dart(),
            self.eta_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::ProgressEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::ProgressEvent>
    for crate::types::ProgressEvent
{
    fn into_into_dart(self) -> crate::types::ProgressEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::ThumbnailBytesOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.position_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::ThumbnailBytesOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::ThumbnailBytesOptions>
    for crate::types::ThumbnailBytesOptions
{
    fn into_into_dart(self) -> crate::types::ThumbnailBytesOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::ThumbnailFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Jpeg => 0.into_dart(),
            Self::Webp => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::ThumbnailFormat {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::ThumbnailFormat>
    for crate::types::ThumbnailFormat
{
    fn into_into_dart(self) -> crate::types::ThumbnailFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::ThumbnailOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.position_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::ThumbnailOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::ThumbnailOptions>
    for crate::types::ThumbnailOptions
{
    fn into_into_dart(self) -> crate::types::ThumbnailOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::VideoCodec {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::H264 => 0.into_dart(),
            Self::Hevc => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::VideoCodec {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::VideoCodec> for crate::types::VideoCodec {
    fn into_into_dart(self) -> crate::types::VideoCodec {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::VideoProcessorError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::error::VideoProcessorError::InvalidInput(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::VideoProcessorError::FileNotFound(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::VideoProcessorError::UnsupportedCodec(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::VideoProcessorError::JobNotFound(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::VideoProcessorError::Cancelled => [4.into_dart()].into_dart(),
            crate::error::VideoProcessorError::IoError(field0) => {
                [5.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::VideoProcessorError::FfmpegError(field0) => {
                [6.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::VideoProcessorError::QueueFull => [7.into_dart()].into_dart(),
            crate::error::VideoProcessorError::Internal(field0) => {
                [8.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::error::VideoProcessorError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::error::VideoProcessorError>
    for crate::error::VideoProcessorError
{
    fn into_into_dart(self) -> crate::error::VideoProcessorError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::VideoQuality {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Low => 0.into_dart(),
            Self::Medium => 1.into_dart(),
            Self::High => 2.into_dart(),
            Self::Custom => 3.into_dart(),
            Self::Instagram => 4.into_dart(),
            Self::Whatsapp => 5.into_dart(),
            Self::Telegram => 6.into_dart(),
            Self::Youtube => 7.into_dart(),
            Self::Lossless => 8.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::VideoQuality {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::VideoQuality> for crate::types::VideoQuality {
    fn into_into_dart(self) -> crate::types::VideoQuality {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::types::ProgressEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::types::BatchThumbnailBytesOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <Vec<u64>>::sse_encode(self.positions_ms, serializer);
        <Option<u32>>::sse_encode(self.width, serializer);
        <Option<u32>>::sse_encode(self.height, serializer);
        <crate::types::ThumbnailFormat>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for crate::types::BatchThumbnailBytesResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<Vec<u8>>>::sse_encode(self.frames, serializer);
    }
}

impl SseEncode for crate::types::BatchThumbnailOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <Option<Vec<String>>>::sse_encode(self.output_paths, serializer);
        <Vec<u64>>::sse_encode(self.positions_ms, serializer);
        <Option<u32>>::sse_encode(self.width, serializer);
        <Option<u32>>::sse_encode(self.height, serializer);
        <crate::types::ThumbnailFormat>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for crate::types::BatchThumbnailResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.paths, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::types::CompressOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <Option<String>>::sse_encode(self.output_path, serializer);
        <crate::types::VideoQuality>::sse_encode(self.quality, serializer);
        <crate::types::VideoCodec>::sse_encode(self.codec, serializer);
        <Option<u8>>::sse_encode(self.crf, serializer);
        <Option<u64>>::sse_encode(self.target_bitrate, serializer);
        <Option<u32>>::sse_encode(self.max_width, serializer);
        <Option<u32>>::sse_encode(self.max_height, serializer);
        <Option<f32>>::sse_encode(self.max_fps, serializer);
        <bool>::sse_encode(self.include_audio, serializer);
        <bool>::sse_encode(self.fast_start, serializer);
        <bool>::sse_encode(self.fragmented_mp4, serializer);
        <bool>::sse_encode(self.prefer_hardware_encoder, serializer);
        <Option<u64>>::sse_encode(self.start_ms, serializer);
        <Option<u64>>::sse_encode(self.end_ms, serializer);
    }
}

impl SseEncode for crate::types::CompressResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <u64>::sse_encode(self.duration_ms, serializer);
        <u64>::sse_encode(self.file_size, serializer);
        <bool>::sse_encode(self.used_hardware_acceleration, serializer);
        <String>::sse_encode(self.encoder_name, serializer);
        <String>::sse_encode(self.pipeline_mode, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::types::JobResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::types::JobResult::Compress(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::types::CompressResult>::sse_encode(field0, serializer);
            }
            crate::types::JobResult::Empty => {
                <i32>::sse_encode(1, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Vec<u8>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::types::MediaInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.duration_ms, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <i32>::sse_encode(self.rotation, serializer);
        <f32>::sse_encode(self.fps, serializer);
        <String>::sse_encode(self.video_codec, serializer);
        <Option<String>>::sse_encode(self.audio_codec, serializer);
        <u64>::sse_encode(self.bitrate, serializer);
        <u64>::sse_encode(self.file_size, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<String>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::types::PreviewFramePixelBuffer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.pts_ms, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <u64>::sse_encode(self.pixel_buffer_ptr, serializer);
    }
}

impl SseEncode for crate::types::PreviewFrameRgba {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.pts_ms, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <Vec<u8>>::sse_encode(self.rgba, serializer);
    }
}

impl SseEncode for crate::types::ProcessingPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::types::ProcessingPhase::Probing => 0,
                crate::types::ProcessingPhase::Decoding => 1,
                crate::types::ProcessingPhase::Encoding => 2,
                crate::types::ProcessingPhase::Muxing => 3,
                crate::types::ProcessingPhase::Thumbnail => 4,
                crate::types::ProcessingPhase::Done => 5,
                crate::types::ProcessingPhase::Cancelled => 6,
                crate::types::ProcessingPhase::Failed => 7,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::types::ProgressEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.job_id, serializer);
        <crate::types::ProcessingPhase>::sse_encode(self.phase, serializer);
        <f32>::sse_encode(self.percent, serializer);
        <u64>::sse_encode(self.frame, serializer);
        <f32>::sse_encode(self.fps, serializer);
        <u64>::sse_encode(self.eta_ms, serializer);
    }
}

impl SseEncode for crate::types::ThumbnailBytesOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <u64>::sse_encode(self.position_ms, serializer);
        <Option<u32>>::sse_encode(self.width, serializer);
        <Option<u32>>::sse_encode(self.height, serializer);
        <crate::types::ThumbnailFormat>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for crate::types::ThumbnailFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::types::ThumbnailFormat::Jpeg => 0,
                crate::types::ThumbnailFormat::Webp => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::types::ThumbnailOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <Option<String>>::sse_encode(self.output_path, serializer);
        <u64>::sse_encode(self.position_ms, serializer);
        <Option<u32>>::sse_encode(self.width, serializer);
        <Option<u32>>::sse_encode(self.height, serializer);
        <crate::types::ThumbnailFormat>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::types::VideoCodec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::types::VideoCodec::H264 => 0,
                crate::types::VideoCodec::Hevc => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::error::VideoProcessorError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::error::VideoProcessorError::InvalidInput(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::VideoProcessorError::FileNotFound(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::VideoProcessorError::UnsupportedCodec(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::VideoProcessorError::JobNotFound(field0) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::VideoProcessorError::Cancelled => {
                <i32>::sse_encode(4, serializer);
            }
            crate::error::VideoProcessorError::IoError(field0) => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::VideoProcessorError::FfmpegError(field0) => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::VideoProcessorError::QueueFull => {
                <i32>::sse_encode(7, serializer);
            }
            crate::error::VideoProcessorError::Internal(field0) => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::types::VideoQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::types::VideoQuality::Low => 0,
                crate::types::VideoQuality::Medium => 1,
                crate::types::VideoQuality::High => 2,
                crate::types::VideoQuality::Custom => 3,
                crate::types::VideoQuality::Instagram => 4,
                crate::types::VideoQuality::Whatsapp => 5,
                crate::types::VideoQuality::Telegram => 6,
                crate::types::VideoQuality::Youtube => 7,
                crate::types::VideoQuality::Lossless => 8,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
