// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Bakes multiple raster overlay layers and vector paint strokes onto a base RGBA buffer.
RgbaImageBuffer bakeLayersOnRgba({
  required RgbaImageBuffer buffer,
  required List<RasterLayerInput> rasterLayers,
  required List<PaintStrokeInput> paintStrokes,
}) => RustLib.instance.api.crateApiLayersBakeLayersOnRgba(
  buffer: buffer,
  rasterLayers: rasterLayers,
  paintStrokes: paintStrokes,
);

/// Input representation for a vector paint stroke.
class PaintStrokeInput {
  /// List of 2D points along the stroke path.
  final List<(double, double)> points;

  /// Color red channel.
  final int colorR;

  /// Color green channel.
  final int colorG;

  /// Color blue channel.
  final int colorB;

  /// Color alpha channel.
  final int colorA;

  /// Stroke width/thickness in pixels.
  final double width;

  /// Opacity factor (0.0 to 1.0) of the stroke.
  final double opacity;

  /// When true, clears painted pixels along the stroke (Sprint 9 eraser).
  final bool erase;

  /// Brush kind index (0=pen, 1=marker, 2=highlighter, 3=eraser, 4=neon).
  final int brushKind;

  /// True if the shape/stroke is filled.
  final bool filled;

  const PaintStrokeInput({
    required this.points,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
    required this.width,
    required this.opacity,
    required this.erase,
    required this.brushKind,
    required this.filled,
  });

  @override
  int get hashCode =>
      points.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode ^
      width.hashCode ^
      opacity.hashCode ^
      erase.hashCode ^
      brushKind.hashCode ^
      filled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaintStrokeInput &&
          runtimeType == other.runtimeType &&
          points == other.points &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA &&
          width == other.width &&
          opacity == other.opacity &&
          erase == other.erase &&
          brushKind == other.brushKind &&
          filled == other.filled;
}

/// Input representation for a raster overlay layer (e.g. sticker or image badge).
class RasterLayerInput {
  /// Decoded raw pixels of the overlay image.
  final Uint8List pixels;

  /// Width of the overlay image in pixels.
  final int width;

  /// Height of the overlay image in pixels.
  final int height;

  /// Horizontal center position relative to base image width.
  final double centerX;

  /// Vertical center position relative to base image height.
  final double centerY;

  /// Scale factor of the overlay.
  final double scale;

  /// Rotation angle of the overlay in radians.
  final double rotationRad;

  /// Opacity factor (0.0 to 1.0) of the overlay.
  final double opacity;

  const RasterLayerInput({
    required this.pixels,
    required this.width,
    required this.height,
    required this.centerX,
    required this.centerY,
    required this.scale,
    required this.rotationRad,
    required this.opacity,
  });

  @override
  int get hashCode =>
      pixels.hashCode ^
      width.hashCode ^
      height.hashCode ^
      centerX.hashCode ^
      centerY.hashCode ^
      scale.hashCode ^
      rotationRad.hashCode ^
      opacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RasterLayerInput &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          width == other.width &&
          height == other.height &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          scale == other.scale &&
          rotationRad == other.rotationRad &&
          opacity == other.opacity;
}
