// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ffmpeg_version_string`, `hw_decode_enabled`, `log_decode_capabilities`, `probe_decode_capabilities_inner`, `release_media_video_frame_pixel_buffer`, `stop_demuxer_session`, `update_time_internal`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioPlayerState`, `PacketQueueInner`, `PlaybackClockInner`, `PlaybackSession`, `SendSafeStream`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `present_frame`, `present_frame`, `pts_ms`, `pts_ms`, `set_audio_clock`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `dequeue_best_for_time`, `dequeue`, `enqueue_video`, `enqueue`, `flush_video`, `flush`, `is_empty`, `latest_pts`, `len`, `max_size`, `new`

/// Probe linked FFmpeg once (safe to call from Dart at startup).
Future<DecodeCapabilities> probeDecodeCapabilities() =>
    RustLib.instance.api.crateApiRuntimeProbeDecodeCapabilities();

Future<void> ensureFfmpegInitialized() =>
    RustLib.instance.api.crateApiRuntimeEnsureFfmpegInitialized();

Future<PixelBufferHandoff?> mediaVideoFrameIntoPixelBufferHandoff({
  required MediaVideoFrame frame,
}) => RustLib.instance.api.crateApiRuntimeMediaVideoFrameIntoPixelBufferHandoff(
  frame: frame,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < FrameQueue < AudioFrame > >>>
abstract class ArcFrameQueueAudioFrame implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < FrameQueue < MediaVideoFrame > >>>
abstract class ArcFrameQueueMediaVideoFrame implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < PacketQueue >>>
abstract class ArcPacketQueue implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < PlaybackClock >>>
abstract class ArcPlaybackClock implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioRuntime>>
abstract class AudioRuntime implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioRuntime> newInstance({
    required ArcPacketQueue packetQueue,
    required ArcFrameQueueAudioFrame frameQueue,
    required ArcPlaybackClock clock,
  }) => RustLib.instance.api.crateApiRuntimeAudioRuntimeNew(
    packetQueue: packetQueue,
    frameQueue: frameQueue,
    clock: clock,
  );

  Future<void> start();

  Future<void> stop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GpuPresenter>>
abstract class GpuPresenter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<GpuPresenter> newInstance({required int textureId}) =>
      RustLib.instance.api.crateApiRuntimeGpuPresenterNew(textureId: textureId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaPlaybackEngine>>
abstract class MediaPlaybackEngine implements RustOpaqueInterface {
  /// Audio clock in ms (for Dart diagnostics / A/V drift display).
  /// Returns 0 until audio begins playing.
  Future<BigInt> getAudioClockMs();

  Future<BigInt> getAudioFrameQueueLen();

  Future<BigInt> getAudioPacketQueueLen();

  Future<Float32List> getAudioWaveform();

  /// Audio clock minus latest decoded video PTS (0 when in sync).
  Future<BigInt> getAvDriftMs();

  /// Phase 0: snapshot of linked FFmpeg / VideoToolbox decoder availability.
  Future<DecodeCapabilities> getDecodeCapabilities();

  Future<BigInt> getDurationMs();

  Future<BigInt> getLastPresentedPtsMs();

  /// PTS of the newest decoded video frame still in the queue (0 if empty).
  Future<BigInt> getLatestDecodedVideoPtsMs();

  /// Master playback position in ms.
  ///
  /// Uses the sample-accurate **audio device clock** when audio is actively
  /// playing — this eliminates drift between the wall clock and the hardware
  /// audio output, which is the primary reason video lags behind audio.
  ///
  /// Falls back to the software wall clock during buffering, pause, and seek.
  Future<BigInt> getMediaTimeMs();

  Future<PlaybackState> getPlaybackState();

  Future<BigInt> getVideoFrameQueueLen();

  Future<BigInt> getVideoPacketQueueLen();

  /// Wall-clock playback position (Instant-based), without audio preference.
  Future<BigInt> getWallClockMs();

  /// Audio-vs-presented drift (ms) that triggers automatic demuxer hard resync.
  Future<BigInt> hardResyncDriftThresholdMs();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MediaPlaybackEngine> newInstance({
    required int textureId,
    required BigInt maxQueueSize,
    required int previewMaxEdge,
  }) => RustLib.instance.api.crateApiRuntimeMediaPlaybackEngineNew(
    textureId: textureId,
    maxQueueSize: maxQueueSize,
    previewMaxEdge: previewMaxEdge,
  );

  Future<void> openFile({required String path});

  Future<void> pause();

  /// Presenter tick interval in ms (~30 fps).
  Future<BigInt> presenterIntervalMs();

  Future<bool> pushAudioPacket({required MediaPacket packet});

  Future<bool> pushVideoPacket({required MediaPacket packet});

  Future<void> seek({required BigInt timeMs});

  Future<void> setRate({required double rate});

  Future<void> start();

  Future<void> stop();

  Future<AudioFrame?> takeAudioFrame();

  /// Returns the frame selected by [`PresenterRuntime`] (~30 fps), not the raw decode queue.
  Future<MediaVideoFrame?> takeVideoFrame();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PacketQueue>>
abstract class PacketQueue implements RustOpaqueInterface {
  Future<void> close();

  Future<void> flush();

  Future<bool> isEmpty();

  Future<BigInt> len();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PacketQueue> newInstance({required BigInt maxSize}) =>
      RustLib.instance.api.crateApiRuntimePacketQueueNew(maxSize: maxSize);

  Future<QueuePacket?> pop();

  Future<bool> push({required QueuePacket packet});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaybackClock>>
abstract class PlaybackClock implements RustOpaqueInterface {
  Future<void> advancePresentedPts({required BigInt ptsMs});

  Future<BigInt> getLastPresentedPtsMs();

  Future<BigInt> getMediaTimeMs();

  Future<PlaybackState> getState();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PlaybackClock> newInstance() =>
      RustLib.instance.api.crateApiRuntimePlaybackClockNew();

  Future<void> pause();

  /// Clears a stale presented PTS after backward seek (presented >> audio).
  Future<void> resetPresentedPtsForSeek({required BigInt toMs});

  Future<void> seek({required BigInt timeMs});

  /// Called when the seek is complete — resumes the appropriate playback state.
  Future<void> seekComplete({required bool wasPlaying});

  Future<void> setRate({required double rate});

  Future<void> start();

  /// Keep the wall clock aligned with the audio sample clock during playback.
  Future<void> syncFromAudioMs({required BigInt audioMs});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QueuePacket>>
abstract class QueuePacket implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VideoRuntime>>
abstract class VideoRuntime implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VideoRuntime> newInstance({
    required ArcPacketQueue packetQueue,
    required ArcFrameQueueMediaVideoFrame frameQueue,
    required ArcPlaybackClock clock,
    required int previewMaxEdge,
  }) => RustLib.instance.api.crateApiRuntimeVideoRuntimeNew(
    packetQueue: packetQueue,
    frameQueue: frameQueue,
    clock: clock,
    previewMaxEdge: previewMaxEdge,
  );

  Future<void> start();

  Future<void> stop();
}

abstract class HasPts {
  Future<BigInt> ptsMs();
}

/// Decoded audio frame (stereo PCM f32 samples).
class AudioFrame {
  final BigInt ptsMs;
  final int sampleRate;
  final int channels;
  final Float32List samples;

  const AudioFrame({
    required this.ptsMs,
    required this.sampleRate,
    required this.channels,
    required this.samples,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      samples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFrame &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          samples == other.samples;
}

/// Phase 0 diagnostic: which decoders exist in the **linked** FFmpeg build.
class DecodeCapabilities {
  /// HEVC + VideoToolbox hwaccel available in linked FFmpeg.
  final bool hevcVideotoolbox;

  /// H.264 + VideoToolbox hwaccel available in linked FFmpeg.
  final bool h264Videotoolbox;

  /// True when `VFP_DISABLE_HW_DECODE` is set.
  final bool hwDecodeDisabledEnv;

  /// libavutil version string (e.g. `59.39.100`).
  final String ffmpegVersion;

  /// Human-readable readiness for 4K iPhone HEVC preview.
  final bool readyForHevcHw;

  /// Hint when HW decoders are missing from the dylib FFmpeg.
  final String hint;

  const DecodeCapabilities({
    required this.hevcVideotoolbox,
    required this.h264Videotoolbox,
    required this.hwDecodeDisabledEnv,
    required this.ffmpegVersion,
    required this.readyForHevcHw,
    required this.hint,
  });

  @override
  int get hashCode =>
      hevcVideotoolbox.hashCode ^
      h264Videotoolbox.hashCode ^
      hwDecodeDisabledEnv.hashCode ^
      ffmpegVersion.hashCode ^
      readyForHevcHw.hashCode ^
      hint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodeCapabilities &&
          runtimeType == other.runtimeType &&
          hevcVideotoolbox == other.hevcVideotoolbox &&
          h264Videotoolbox == other.h264Videotoolbox &&
          hwDecodeDisabledEnv == other.hwDecodeDisabledEnv &&
          ffmpegVersion == other.ffmpegVersion &&
          readyForHevcHw == other.readyForHevcHw &&
          hint == other.hint;
}

/// A simplified demuxed media packet.
class MediaPacket {
  final BigInt ptsMs;
  final BigInt dtsMs;
  final BigInt streamIndex;
  final bool isKeyframe;
  final Uint8List data;

  const MediaPacket({
    required this.ptsMs,
    required this.dtsMs,
    required this.streamIndex,
    required this.isKeyframe,
    required this.data,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      dtsMs.hashCode ^
      streamIndex.hashCode ^
      isKeyframe.hashCode ^
      data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaPacket &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          dtsMs == other.dtsMs &&
          streamIndex == other.streamIndex &&
          isKeyframe == other.isKeyframe &&
          data == other.data;
}

/// Decoded video frame for presentation.
///
/// **RGBA path:** [pixels] is `width × height × 4`, [pixel_buffer_ptr] is 0.
/// **Apple HW path:** [pixel_buffer_ptr] is a retained BGRA `CVPixelBuffer*`; [pixels] is empty.
class MediaVideoFrame {
  final BigInt ptsMs;
  final int width;
  final int height;
  final Uint8List pixels;
  final BigInt pixelBufferPtr;

  const MediaVideoFrame({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.pixels,
    required this.pixelBufferPtr,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixels.hashCode ^
      pixelBufferPtr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaVideoFrame &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels &&
          pixelBufferPtr == other.pixelBufferPtr;
}

/// Hand off `CVPixelBuffer` to Flutter without releasing on [MediaVideoFrame] drop.
class PixelBufferHandoff {
  final BigInt ptsMs;
  final int width;
  final int height;
  final BigInt pixelBufferPtr;

  const PixelBufferHandoff({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.pixelBufferPtr,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixelBufferPtr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PixelBufferHandoff &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          pixelBufferPtr == other.pixelBufferPtr;
}

/// State of the playback clock.
enum PlaybackState { idle, playing, paused, seeking, ended }
