// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class VideoForgeError with _$VideoForgeError {
  const VideoForgeError._();

  const factory VideoForgeError.invalidInput(String field0) =
      VideoForgeError_InvalidInput;
  const factory VideoForgeError.fileNotFound(String field0) =
      VideoForgeError_FileNotFound;
  const factory VideoForgeError.unsupportedCodec(String field0) =
      VideoForgeError_UnsupportedCodec;
  const factory VideoForgeError.jobNotFound(String field0) =
      VideoForgeError_JobNotFound;
  const factory VideoForgeError.cancelled() = VideoForgeError_Cancelled;
  const factory VideoForgeError.ioError(String field0) =
      VideoForgeError_IoError;
  const factory VideoForgeError.ffmpegError(String field0) =
      VideoForgeError_FfmpegError;
  const factory VideoForgeError.queueFull() = VideoForgeError_QueueFull;
  const factory VideoForgeError.internal(String field0) =
      VideoForgeError_Internal;

  /// Recovery cooldown active (engine::seek_recovery). The caller
  /// may escalate to a more aggressive strategy or skip the
  /// operation. Distinct from `Internal` so callers can pattern-match
  /// on it.
  const factory VideoForgeError.cooldownActive(String field0, BigInt field1) =
      VideoForgeError_CooldownActive;

  /// All attempts of a particular recovery strategy have been
  /// exhausted. Caller should treat the session as unrecoverable for
  /// the current failure.
  const factory VideoForgeError.recoveryBudgetExhausted(String field0) =
      VideoForgeError_RecoveryBudgetExhausted;

  Future<String> errorCode() =>
      RustLib.instance.api.crateErrorVideoForgeErrorErrorCode(that: this);

  Future<String> errorMessage() =>
      RustLib.instance.api.crateErrorVideoForgeErrorErrorMessage(that: this);
}
