// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'pipeline/preview.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VideoPreviewSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  VideoPreviewSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    dynamic raw,
  );

  @protected
  VideoPreviewSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    dynamic raw,
  );

  @protected
  VideoPreviewSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<PlaybackFrame> dco_decode_StreamSink_playback_frame_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioTrackInput dco_decode_audio_track_input(dynamic raw);

  @protected
  BatchThumbnailBytesOptions dco_decode_batch_thumbnail_bytes_options(
    dynamic raw,
  );

  @protected
  BatchThumbnailBytesResult dco_decode_batch_thumbnail_bytes_result(
    dynamic raw,
  );

  @protected
  BatchThumbnailOptions dco_decode_batch_thumbnail_options(dynamic raw);

  @protected
  BatchThumbnailResult dco_decode_batch_thumbnail_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BatchThumbnailBytesOptions
  dco_decode_box_autoadd_batch_thumbnail_bytes_options(dynamic raw);

  @protected
  BatchThumbnailOptions dco_decode_box_autoadd_batch_thumbnail_options(
    dynamic raw,
  );

  @protected
  CompressOptions dco_decode_box_autoadd_compress_options(dynamic raw);

  @protected
  CompressResult dco_decode_box_autoadd_compress_result(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  OutputProfile dco_decode_box_autoadd_output_profile(dynamic raw);

  @protected
  PreviewFramePixelBuffer dco_decode_box_autoadd_preview_frame_pixel_buffer(
    dynamic raw,
  );

  @protected
  PreviewFrameRgba dco_decode_box_autoadd_preview_frame_rgba(dynamic raw);

  @protected
  ThumbnailBytesOptions dco_decode_box_autoadd_thumbnail_bytes_options(
    dynamic raw,
  );

  @protected
  ThumbnailOptions dco_decode_box_autoadd_thumbnail_options(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  VideoForgeError dco_decode_box_autoadd_video_forge_error(dynamic raw);

  @protected
  BurnInOverlay dco_decode_burn_in_overlay(dynamic raw);

  @protected
  CompressOptions dco_decode_compress_options(dynamic raw);

  @protected
  CompressResult dco_decode_compress_result(dynamic raw);

  @protected
  DecoderCacheStatsDto dco_decode_decoder_cache_stats_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  JobResult dco_decode_job_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioTrackInput> dco_decode_list_audio_track_input(dynamic raw);

  @protected
  List<BurnInOverlay> dco_decode_list_burn_in_overlay(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ThumbnailDecodeStatus> dco_decode_list_thumbnail_decode_status(
    dynamic raw,
  );

  @protected
  MediaInfo dco_decode_media_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  OutputProfile? dco_decode_opt_box_autoadd_output_profile(dynamic raw);

  @protected
  PreviewFramePixelBuffer?
  dco_decode_opt_box_autoadd_preview_frame_pixel_buffer(dynamic raw);

  @protected
  PreviewFrameRgba? dco_decode_opt_box_autoadd_preview_frame_rgba(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  OutputProfile dco_decode_output_profile(dynamic raw);

  @protected
  PlaybackFrame dco_decode_playback_frame(dynamic raw);

  @protected
  PreviewFramePixelBuffer dco_decode_preview_frame_pixel_buffer(dynamic raw);

  @protected
  PreviewFrameRgba dco_decode_preview_frame_rgba(dynamic raw);

  @protected
  ProcessingPhase dco_decode_processing_phase(dynamic raw);

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_usize_usize(dynamic raw);

  @protected
  ThumbnailBytesOptions dco_decode_thumbnail_bytes_options(dynamic raw);

  @protected
  ThumbnailDecodeStatus dco_decode_thumbnail_decode_status(dynamic raw);

  @protected
  ThumbnailFormat dco_decode_thumbnail_format(dynamic raw);

  @protected
  ThumbnailOptions dco_decode_thumbnail_options(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoCodec dco_decode_video_codec(dynamic raw);

  @protected
  VideoForgeError dco_decode_video_forge_error(dynamic raw);

  @protected
  VideoQuality dco_decode_video_quality(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  VideoPreviewSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    SseDeserializer deserializer,
  );

  @protected
  VideoPreviewSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    SseDeserializer deserializer,
  );

  @protected
  VideoPreviewSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PlaybackFrame> sse_decode_StreamSink_playback_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioTrackInput sse_decode_audio_track_input(SseDeserializer deserializer);

  @protected
  BatchThumbnailBytesOptions sse_decode_batch_thumbnail_bytes_options(
    SseDeserializer deserializer,
  );

  @protected
  BatchThumbnailBytesResult sse_decode_batch_thumbnail_bytes_result(
    SseDeserializer deserializer,
  );

  @protected
  BatchThumbnailOptions sse_decode_batch_thumbnail_options(
    SseDeserializer deserializer,
  );

  @protected
  BatchThumbnailResult sse_decode_batch_thumbnail_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BatchThumbnailBytesOptions
  sse_decode_box_autoadd_batch_thumbnail_bytes_options(
    SseDeserializer deserializer,
  );

  @protected
  BatchThumbnailOptions sse_decode_box_autoadd_batch_thumbnail_options(
    SseDeserializer deserializer,
  );

  @protected
  CompressOptions sse_decode_box_autoadd_compress_options(
    SseDeserializer deserializer,
  );

  @protected
  CompressResult sse_decode_box_autoadd_compress_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  OutputProfile sse_decode_box_autoadd_output_profile(
    SseDeserializer deserializer,
  );

  @protected
  PreviewFramePixelBuffer sse_decode_box_autoadd_preview_frame_pixel_buffer(
    SseDeserializer deserializer,
  );

  @protected
  PreviewFrameRgba sse_decode_box_autoadd_preview_frame_rgba(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailBytesOptions sse_decode_box_autoadd_thumbnail_bytes_options(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailOptions sse_decode_box_autoadd_thumbnail_options(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  VideoForgeError sse_decode_box_autoadd_video_forge_error(
    SseDeserializer deserializer,
  );

  @protected
  BurnInOverlay sse_decode_burn_in_overlay(SseDeserializer deserializer);

  @protected
  CompressOptions sse_decode_compress_options(SseDeserializer deserializer);

  @protected
  CompressResult sse_decode_compress_result(SseDeserializer deserializer);

  @protected
  DecoderCacheStatsDto sse_decode_decoder_cache_stats_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  JobResult sse_decode_job_result(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioTrackInput> sse_decode_list_audio_track_input(
    SseDeserializer deserializer,
  );

  @protected
  List<BurnInOverlay> sse_decode_list_burn_in_overlay(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ThumbnailDecodeStatus> sse_decode_list_thumbnail_decode_status(
    SseDeserializer deserializer,
  );

  @protected
  MediaInfo sse_decode_media_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  OutputProfile? sse_decode_opt_box_autoadd_output_profile(
    SseDeserializer deserializer,
  );

  @protected
  PreviewFramePixelBuffer?
  sse_decode_opt_box_autoadd_preview_frame_pixel_buffer(
    SseDeserializer deserializer,
  );

  @protected
  PreviewFrameRgba? sse_decode_opt_box_autoadd_preview_frame_rgba(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  OutputProfile sse_decode_output_profile(SseDeserializer deserializer);

  @protected
  PlaybackFrame sse_decode_playback_frame(SseDeserializer deserializer);

  @protected
  PreviewFramePixelBuffer sse_decode_preview_frame_pixel_buffer(
    SseDeserializer deserializer,
  );

  @protected
  PreviewFrameRgba sse_decode_preview_frame_rgba(SseDeserializer deserializer);

  @protected
  ProcessingPhase sse_decode_processing_phase(SseDeserializer deserializer);

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt) sse_decode_record_usize_usize(SseDeserializer deserializer);

  @protected
  ThumbnailBytesOptions sse_decode_thumbnail_bytes_options(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailDecodeStatus sse_decode_thumbnail_decode_status(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailFormat sse_decode_thumbnail_format(SseDeserializer deserializer);

  @protected
  ThumbnailOptions sse_decode_thumbnail_options(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoCodec sse_decode_video_codec(SseDeserializer deserializer);

  @protected
  VideoForgeError sse_decode_video_forge_error(SseDeserializer deserializer);

  @protected
  VideoQuality sse_decode_video_quality(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    VideoPreviewSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    VideoPreviewSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    VideoPreviewSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_playback_frame_Sse(
    RustStreamSink<PlaybackFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_track_input(
    AudioTrackInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_thumbnail_bytes_options(
    BatchThumbnailBytesOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_thumbnail_bytes_result(
    BatchThumbnailBytesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_thumbnail_options(
    BatchThumbnailOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_thumbnail_result(
    BatchThumbnailResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_batch_thumbnail_bytes_options(
    BatchThumbnailBytesOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_batch_thumbnail_options(
    BatchThumbnailOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_compress_options(
    CompressOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_compress_result(
    CompressResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_output_profile(
    OutputProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_preview_frame_pixel_buffer(
    PreviewFramePixelBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_preview_frame_rgba(
    PreviewFrameRgba self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thumbnail_bytes_options(
    ThumbnailBytesOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thumbnail_options(
    ThumbnailOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_forge_error(
    VideoForgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_burn_in_overlay(BurnInOverlay self, SseSerializer serializer);

  @protected
  void sse_encode_compress_options(
    CompressOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compress_result(
    CompressResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoder_cache_stats_dto(
    DecoderCacheStatsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_job_result(JobResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_track_input(
    List<AudioTrackInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_burn_in_overlay(
    List<BurnInOverlay> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thumbnail_decode_status(
    List<ThumbnailDecodeStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_info(MediaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_output_profile(
    OutputProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_preview_frame_pixel_buffer(
    PreviewFramePixelBuffer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_preview_frame_rgba(
    PreviewFrameRgba? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_output_profile(OutputProfile self, SseSerializer serializer);

  @protected
  void sse_encode_playback_frame(PlaybackFrame self, SseSerializer serializer);

  @protected
  void sse_encode_preview_frame_pixel_buffer(
    PreviewFramePixelBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_preview_frame_rgba(
    PreviewFrameRgba self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processing_phase(
    ProcessingPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_bytes_options(
    ThumbnailBytesOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_decode_status(
    ThumbnailDecodeStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_format(
    ThumbnailFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_options(
    ThumbnailOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_codec(VideoCodec self, SseSerializer serializer);

  @protected
  void sse_encode_video_forge_error(
    VideoForgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_video_quality(VideoQuality self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoPreviewSession(
    int ptr,
  );
}
