// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

/// Background audio lane for export mux (paths must be local FFmpeg-readable files).
class AudioTrackInput {
  final String sourcePath;
  final BigInt sourceStartMs;
  final BigInt durationMs;
  final BigInt timelineStartMs;
  final double volume;
  final bool muted;

  const AudioTrackInput({
    required this.sourcePath,
    required this.sourceStartMs,
    required this.durationMs,
    required this.timelineStartMs,
    required this.volume,
    required this.muted,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      sourceStartMs.hashCode ^
      durationMs.hashCode ^
      timelineStartMs.hashCode ^
      volume.hashCode ^
      muted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioTrackInput &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          sourceStartMs == other.sourceStartMs &&
          durationMs == other.durationMs &&
          timelineStartMs == other.timelineStartMs &&
          volume == other.volume &&
          muted == other.muted;
}

/// Batch in-memory thumbnails for UI previews (filmstrip, scrubber fallback).
class BatchThumbnailBytesOptions {
  final String inputPath;
  final Uint64List positionsMs;
  final int? width;
  final int? height;
  final ThumbnailFormat format;

  /// PR #3 (opt-in): see [BatchThumbnailOptions::parallel_decoder_count].
  final int? parallelDecoderCount;

  const BatchThumbnailBytesOptions({
    required this.inputPath,
    required this.positionsMs,
    this.width,
    this.height,
    required this.format,
    this.parallelDecoderCount,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      positionsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      parallelDecoderCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchThumbnailBytesOptions &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          positionsMs == other.positionsMs &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          parallelDecoderCount == other.parallelDecoderCount;
}

class BatchThumbnailBytesResult {
  final List<Uint8List> frames;

  /// PR #3: per-position decode status. Same length as
  /// `positions_ms` in the request.
  final List<ThumbnailDecodeStatus> decodedStatus;

  const BatchThumbnailBytesResult({
    required this.frames,
    required this.decodedStatus,
  });

  @override
  int get hashCode => frames.hashCode ^ decodedStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchThumbnailBytesResult &&
          runtimeType == other.runtimeType &&
          frames == other.frames &&
          decodedStatus == other.decodedStatus;
}

class BatchThumbnailOptions {
  final String inputPath;
  final String outputDir;

  /// When set, length must equal [positions_ms]; each index is written to this path
  /// instead of [output_dir]/thumb_XXXX.ext.
  final List<String>? outputPaths;
  final Uint64List positionsMs;
  final int? width;
  final int? height;
  final ThumbnailFormat format;

  /// PR #3 (opt-in): when `Some(n) > 0`, the batch opens up to `n`
  /// parallel demuxer instances and shards the positions across them
  /// (decode stays single-threaded per demuxer; encode is already
  /// parallel via rayon). Default 0 = single-demuxer. Useful for
  /// filmstrip batches on long-GOP iPhone HEVC where the demuxer
  /// open + first-frame-decode is the bottleneck.
  final int? parallelDecoderCount;

  const BatchThumbnailOptions({
    required this.inputPath,
    required this.outputDir,
    this.outputPaths,
    required this.positionsMs,
    this.width,
    this.height,
    required this.format,
    this.parallelDecoderCount,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputDir.hashCode ^
      outputPaths.hashCode ^
      positionsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      parallelDecoderCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchThumbnailOptions &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputDir == other.outputDir &&
          outputPaths == other.outputPaths &&
          positionsMs == other.positionsMs &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          parallelDecoderCount == other.parallelDecoderCount;
}

class BatchThumbnailResult {
  final List<String> paths;

  /// PR #3: per-position decode status. Same length as
  /// `positions_ms` in the request. Use this to flag approximate
  /// thumbnails in a UI filmstrip.
  final List<ThumbnailDecodeStatus> decodedStatus;

  const BatchThumbnailResult({
    required this.paths,
    required this.decodedStatus,
  });

  @override
  int get hashCode => paths.hashCode ^ decodedStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchThumbnailResult &&
          runtimeType == other.runtimeType &&
          paths == other.paths &&
          decodedStatus == other.decodedStatus;
}

/// One overlay layer baked to a PNG with alpha (paths from Flutter export rasterizer).
class BurnInOverlay {
  final String imagePath;

  /// Visible on [start_ms, end_ms) in source timeline milliseconds.
  final BigInt startMs;
  final BigInt endMs;

  /// Normalized anchor 0–1 (top-left origin), matches Flutter compositor.
  final double anchorX;
  final double anchorY;
  final BigInt fadeInMs;
  final BigInt fadeOutMs;

  const BurnInOverlay({
    required this.imagePath,
    required this.startMs,
    required this.endMs,
    required this.anchorX,
    required this.anchorY,
    required this.fadeInMs,
    required this.fadeOutMs,
  });

  @override
  int get hashCode =>
      imagePath.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      anchorX.hashCode ^
      anchorY.hashCode ^
      fadeInMs.hashCode ^
      fadeOutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BurnInOverlay &&
          runtimeType == other.runtimeType &&
          imagePath == other.imagePath &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          anchorX == other.anchorX &&
          anchorY == other.anchorY &&
          fadeInMs == other.fadeInMs &&
          fadeOutMs == other.fadeOutMs;
}

class CompressOptions {
  final String inputPath;
  final String? outputPath;
  final VideoQuality quality;
  final VideoCodec codec;
  final int? crf;
  final BigInt? targetBitrate;
  final int? maxWidth;
  final int? maxHeight;
  final double? maxFps;
  final bool includeAudio;

  /// PR #4 (deprecated): use [output_profile] instead. Retained for
  /// one release so existing 2.x callers keep compiling.
  /// `true` + `fragmented_mp4 = false` -> `ProgressiveMp4 { fast_start: true }`.
  /// `fragmented_mp4 = true` (regardless of fast_start) -> `FragmentedMp4 { fragment_duration_ms: 2000 }`.
  final bool fastStart;

  /// PR #4 (deprecated): see [output_profile].
  final bool fragmentedMp4;

  /// PR #4: output container profile. When `None`, the deprecated
  /// `fast_start` + `fragmented_mp4` booleans are used. When `Some`,
  /// `output_profile` wins. New code should always set this.
  final OutputProfile? outputProfile;
  final bool preferHardwareEncoder;

  /// Inclusive clip start in milliseconds (0 = beginning).
  final BigInt? startMs;

  /// Inclusive clip end in milliseconds (None = end of file).
  final BigInt? endMs;

  /// Pre-rasterized overlay PNGs (Flutter) composited on each encoded frame.
  final List<BurnInOverlay> burnInOverlays;

  /// External background audio mixed on export (streaming decode; empty = no added tracks).
  final List<AudioTrackInput> audioTracks;

  /// When true, omit the source file’s embedded audio from the mix (only added tracks).
  final bool muteOriginalAudio;

  const CompressOptions({
    required this.inputPath,
    this.outputPath,
    required this.quality,
    required this.codec,
    this.crf,
    this.targetBitrate,
    this.maxWidth,
    this.maxHeight,
    this.maxFps,
    required this.includeAudio,
    required this.fastStart,
    required this.fragmentedMp4,
    this.outputProfile,
    required this.preferHardwareEncoder,
    this.startMs,
    this.endMs,
    required this.burnInOverlays,
    required this.audioTracks,
    required this.muteOriginalAudio,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputPath.hashCode ^
      quality.hashCode ^
      codec.hashCode ^
      crf.hashCode ^
      targetBitrate.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      maxFps.hashCode ^
      includeAudio.hashCode ^
      fastStart.hashCode ^
      fragmentedMp4.hashCode ^
      outputProfile.hashCode ^
      preferHardwareEncoder.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      burnInOverlays.hashCode ^
      audioTracks.hashCode ^
      muteOriginalAudio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressOptions &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath &&
          quality == other.quality &&
          codec == other.codec &&
          crf == other.crf &&
          targetBitrate == other.targetBitrate &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          maxFps == other.maxFps &&
          includeAudio == other.includeAudio &&
          fastStart == other.fastStart &&
          fragmentedMp4 == other.fragmentedMp4 &&
          outputProfile == other.outputProfile &&
          preferHardwareEncoder == other.preferHardwareEncoder &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          burnInOverlays == other.burnInOverlays &&
          audioTracks == other.audioTracks &&
          muteOriginalAudio == other.muteOriginalAudio;
}

class CompressResult {
  final String outputPath;
  final BigInt durationMs;
  final BigInt fileSize;
  final bool usedHardwareAcceleration;
  final String encoderName;

  /// How frames reached the encoder: `vt_zero_copy`, `vt_gpu_scale`, `hw_decode+swscale`, `swscale`, `direct`.
  final String pipelineMode;

  const CompressResult({
    required this.outputPath,
    required this.durationMs,
    required this.fileSize,
    required this.usedHardwareAcceleration,
    required this.encoderName,
    required this.pipelineMode,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      durationMs.hashCode ^
      fileSize.hashCode ^
      usedHardwareAcceleration.hashCode ^
      encoderName.hashCode ^
      pipelineMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressResult &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          durationMs == other.durationMs &&
          fileSize == other.fileSize &&
          usedHardwareAcceleration == other.usedHardwareAcceleration &&
          encoderName == other.encoderName &&
          pipelineMode == other.pipelineMode;
}

@freezed
sealed class JobResult with _$JobResult {
  const JobResult._();

  const factory JobResult.compress(CompressResult field0) = JobResult_Compress;
  const factory JobResult.empty() = JobResult_Empty;
}

class MediaInfo {
  final BigInt durationMs;
  final int width;
  final int height;
  final int rotation;
  final double fps;
  final String videoCodec;
  final String? audioCodec;
  final BigInt bitrate;
  final BigInt fileSize;

  /// True for iPhone / camera Dolby Vision HEVC (preview uses software decode on Apple).
  final bool hasDolbyVision;

  /// When true, UI should use session RGBA decode (skip VideoToolbox seek on Apple).
  final bool preferSoftwarePreview;

  const MediaInfo({
    required this.durationMs,
    required this.width,
    required this.height,
    required this.rotation,
    required this.fps,
    required this.videoCodec,
    this.audioCodec,
    required this.bitrate,
    required this.fileSize,
    required this.hasDolbyVision,
    required this.preferSoftwarePreview,
  });

  @override
  int get hashCode =>
      durationMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      rotation.hashCode ^
      fps.hashCode ^
      videoCodec.hashCode ^
      audioCodec.hashCode ^
      bitrate.hashCode ^
      fileSize.hashCode ^
      hasDolbyVision.hashCode ^
      preferSoftwarePreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfo &&
          runtimeType == other.runtimeType &&
          durationMs == other.durationMs &&
          width == other.width &&
          height == other.height &&
          rotation == other.rotation &&
          fps == other.fps &&
          videoCodec == other.videoCodec &&
          audioCodec == other.audioCodec &&
          bitrate == other.bitrate &&
          fileSize == other.fileSize &&
          hasDolbyVision == other.hasDolbyVision &&
          preferSoftwarePreview == other.preferSoftwarePreview;
}

@freezed
sealed class OutputProfile with _$OutputProfile {
  const OutputProfile._();

  /// Single progressive MP4. `fast_start: true` (default) moves the
  /// moov atom to the front of the file so the asset can play before
  /// the download completes. Equivalent to the old
  /// `fast_start: true, fragmented_mp4: false`.
  const factory OutputProfile.progressiveMp4({
    /// Move the moov atom to the front of the file so playback
    /// can start before the download completes. Default: `true`.
    required bool fastStart,
  }) = OutputProfile_ProgressiveMp4;

  /// Fragmented MP4 (CMAF-style). Each fragment is independently
  /// decodable, so the asset is seekable as soon as the first
  /// fragment is downloaded. Pair with HLS / DASH for adaptive
  /// streaming or with social-media uploads that expect fMP4 input.
  /// `fragment_duration_ms` controls the target fragment length
  /// (FFmpeg `movflags=+frag_keyframe+frag_duration_ms=N`).
  const factory OutputProfile.fragmentedMp4({
    /// Target fragment length in milliseconds. Default: `2000`
    /// (matches the HLS default segment length).
    required int fragmentDurationMs,
  }) = OutputProfile_FragmentedMp4;

  /// HTTP Live Streaming (HLS, m3u8 + .ts segments). The output
  /// directory must already exist; FFmpeg writes
  /// `playlist.m3u8` + `segment_NNN.ts` alongside the output path
  /// (the output path is used as a prefix — e.g. `/out/playlist.m3u8`
  /// produces segments at `/out/playlistN.ts`).
  const factory OutputProfile.hls({
    /// Target segment length in milliseconds. Default: `6000`
    /// (Apple's recommended HLS segment length).
    required int segmentDurationMs,

    /// When `true`, FFmpeg also writes a `master.m3u8` with
    /// `#EXT-X-STREAM-INF` tags for adaptive bitrate ladders.
    /// Currently a single rendition is emitted; the master
    /// playlist is correct in shape but lists only one variant.
    required bool masterPlaylist,

    /// HLS protocol version. Default: `6` (HLSv6, supports
    /// fMP4 / CMAF segments). Use `3` for legacy clients.
    required int hlsVersion,
  }) = OutputProfile_Hls;
}

@freezed
sealed class PlaybackFrame with _$PlaybackFrame {
  const PlaybackFrame._();

  const factory PlaybackFrame.rgba(PreviewFrameRgba field0) =
      PlaybackFrame_Rgba;
  const factory PlaybackFrame.pixelBuffer(PreviewFramePixelBuffer field0) =
      PlaybackFrame_PixelBuffer;
}

/// Apple HW preview frame: BGRA `CVPixelBuffer` pointer for zero-copy texture present (V1.4).
class PreviewFramePixelBuffer {
  final BigInt ptsMs;
  final int width;
  final int height;

  /// Native `CVPixelBuffer*` address; call [crate::api::release_preview_pixel_buffer] if not presented.
  final BigInt pixelBufferPtr;

  const PreviewFramePixelBuffer({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.pixelBufferPtr,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixelBufferPtr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewFramePixelBuffer &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          pixelBufferPtr == other.pixelBufferPtr;
}

/// Single decoded preview frame (RGBA8888) for texture upload — Sprint V1.1.
class PreviewFrameRgba {
  final BigInt ptsMs;
  final int width;
  final int height;
  final Uint8List rgba;

  const PreviewFrameRgba({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^ width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewFrameRgba &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// PR #5: preview frame paired with a `ReleaseToken` so the Dart
/// side can hand the underlying buffer back to the Rust pool via a
/// `Finalizer` (no manual `bufferPoolRelease` call required from
/// app code). New code should prefer this struct; the bare
/// [PreviewFrameRgba] is kept for back-compat.
class PreviewFrameRgbaBuf {
  final BigInt ptsMs;
  final int width;
  final int height;
  final Uint8List rgba;

  /// Stable token for [crate::pool::release_buffer_by_token]. The
  /// value `0` means "no token" (the buffer will be released by
  /// the explicit `bufferPoolRelease` path instead).
  final BigInt releaseToken;

  const PreviewFrameRgbaBuf({
    required this.ptsMs,
    required this.width,
    required this.height,
    required this.rgba,
    required this.releaseToken,
  });

  @override
  int get hashCode =>
      ptsMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      rgba.hashCode ^
      releaseToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewFrameRgbaBuf &&
          runtimeType == other.runtimeType &&
          ptsMs == other.ptsMs &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba &&
          releaseToken == other.releaseToken;
}

enum ProcessingPhase {
  probing,
  decoding,
  encoding,
  muxing,
  thumbnail,
  done,
  cancelled,
  failed,
}

class ProgressEvent {
  final String jobId;
  final ProcessingPhase phase;
  final double percent;
  final BigInt frame;
  final double fps;
  final BigInt etaMs;

  const ProgressEvent({
    required this.jobId,
    required this.phase,
    required this.percent,
    required this.frame,
    required this.fps,
    required this.etaMs,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      phase.hashCode ^
      percent.hashCode ^
      frame.hashCode ^
      fps.hashCode ^
      etaMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressEvent &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          phase == other.phase &&
          percent == other.percent &&
          frame == other.frame &&
          fps == other.fps &&
          etaMs == other.etaMs;
}

/// In-memory thumbnail (JPEG/WebP bytes) — no filesystem write.
class ThumbnailBytesOptions {
  final String inputPath;
  final BigInt positionMs;
  final int? width;
  final int? height;
  final ThumbnailFormat format;

  const ThumbnailBytesOptions({
    required this.inputPath,
    required this.positionMs,
    this.width,
    this.height,
    required this.format,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      positionMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbnailBytesOptions &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          positionMs == other.positionMs &&
          width == other.width &&
          height == other.height &&
          format == other.format;
}

/// PR #3: per-position status surfaced from the Rust decode pipeline.
enum ThumbnailDecodeStatus {
  /// Frame decoded at or after the requested position. Most common.
  exact,

  /// The demuxer ran out of packets before reaching the requested
  /// position. The thumbnail is the closest decoded keyframe; the
  /// UI should flag it as approximate.
  nearestKeyframe,
}

enum ThumbnailFormat { jpeg, webp }

class ThumbnailOptions {
  final String inputPath;
  final String? outputPath;
  final BigInt positionMs;
  final int? width;
  final int? height;
  final ThumbnailFormat format;

  const ThumbnailOptions({
    required this.inputPath,
    this.outputPath,
    required this.positionMs,
    this.width,
    this.height,
    required this.format,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputPath.hashCode ^
      positionMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbnailOptions &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath &&
          positionMs == other.positionMs &&
          width == other.width &&
          height == other.height &&
          format == other.format;
}

enum VideoCodec { h264, hevc }

enum VideoQuality {
  low,
  medium,
  high,
  custom,

  /// 1080p, social feed / story style.
  instagram,

  /// 720p, small files for messaging.
  whatsapp,

  /// 720p (max 1280×720), messaging app uploads.
  telegram,

  /// 1080p, higher bitrate for video platforms.
  youtube,

  /// High quality, large output.
  lossless,
}
