// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class VideoProcessorError with _$VideoProcessorError {
  const VideoProcessorError._();

  const factory VideoProcessorError.invalidInput(String field0) =
      VideoProcessorError_InvalidInput;
  const factory VideoProcessorError.fileNotFound(String field0) =
      VideoProcessorError_FileNotFound;
  const factory VideoProcessorError.unsupportedCodec(String field0) =
      VideoProcessorError_UnsupportedCodec;
  const factory VideoProcessorError.jobNotFound(String field0) =
      VideoProcessorError_JobNotFound;
  const factory VideoProcessorError.cancelled() = VideoProcessorError_Cancelled;
  const factory VideoProcessorError.ioError(String field0) =
      VideoProcessorError_IoError;
  const factory VideoProcessorError.ffmpegError(String field0) =
      VideoProcessorError_FfmpegError;
  const factory VideoProcessorError.queueFull() = VideoProcessorError_QueueFull;
  const factory VideoProcessorError.internal(String field0) =
      VideoProcessorError_Internal;

  Future<String> errorCode() =>
      RustLib.instance.api.crateErrorVideoProcessorErrorErrorCode(that: this);

  Future<String> errorMessage() => RustLib.instance.api
      .crateErrorVideoProcessorErrorErrorMessage(that: this);
}
