// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -651265318;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'video_processor_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiActiveJobCount();

  Future<BatchThumbnailBytesResult> crateApiBatchThumbnailBytes({
    required BatchThumbnailBytesOptions options,
  });

  Future<BatchThumbnailResult> crateApiBatchThumbnails({
    required BatchThumbnailOptions options,
  });

  Future<bool> crateApiCancelJob({required String jobId});

  Future<void> crateApiCleanupJob({required String jobId});

  Future<PreviewFrameRgba> crateApiDecodePreviewFrameRgba({
    required String inputPath,
    required BigInt positionMs,
    int? maxEdge,
  });

  Future<MediaInfo> crateApiGetMediaInfo({required String path});

  Future<void> crateApiInitApp();

  Future<void> crateApiInitialize();

  String crateApiPrefetchRemoteInput({
    required String url,
    required String destDir,
  });

  Stream<ProgressEvent> crateApiStartCompress({
    required CompressOptions options,
  });

  Future<String> crateApiThumbnail({required ThumbnailOptions options});

  Future<Uint8List> crateApiThumbnailBytes({
    required ThumbnailBytesOptions options,
  });

  Future<String> crateErrorVideoProcessorErrorErrorCode({
    required VideoProcessorError that,
  });

  Future<String> crateErrorVideoProcessorErrorErrorMessage({
    required VideoProcessorError that,
  });

  Future<JobResult> crateApiWaitForJob({required String jobId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiActiveJobCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiActiveJobCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveJobCountConstMeta =>
      const TaskConstMeta(debugName: "active_job_count", argNames: []);

  @override
  Future<BatchThumbnailBytesResult> crateApiBatchThumbnailBytes({
    required BatchThumbnailBytesOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_batch_thumbnail_bytes_options(
            options,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_batch_thumbnail_bytes_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatchThumbnailBytesConstMeta,
        argValues: [options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatchThumbnailBytesConstMeta =>
      const TaskConstMeta(
        debugName: "batch_thumbnail_bytes",
        argNames: ["options"],
      );

  @override
  Future<BatchThumbnailResult> crateApiBatchThumbnails({
    required BatchThumbnailOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_batch_thumbnail_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_batch_thumbnail_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatchThumbnailsConstMeta,
        argValues: [options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatchThumbnailsConstMeta =>
      const TaskConstMeta(debugName: "batch_thumbnails", argNames: ["options"]);

  @override
  Future<bool> crateApiCancelJob({required String jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCancelJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCancelJobConstMeta =>
      const TaskConstMeta(debugName: "cancel_job", argNames: ["jobId"]);

  @override
  Future<void> crateApiCleanupJob({required String jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCleanupJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCleanupJobConstMeta =>
      const TaskConstMeta(debugName: "cleanup_job", argNames: ["jobId"]);

  @override
  Future<PreviewFrameRgba> crateApiDecodePreviewFrameRgba({
    required String inputPath,
    required BigInt positionMs,
    int? maxEdge,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_u_64(positionMs, serializer);
          sse_encode_opt_box_autoadd_u_32(maxEdge, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_preview_frame_rgba,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDecodePreviewFrameRgbaConstMeta,
        argValues: [inputPath, positionMs, maxEdge],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecodePreviewFrameRgbaConstMeta =>
      const TaskConstMeta(
        debugName: "decode_preview_frame_rgba",
        argNames: ["inputPath", "positionMs", "maxEdge"],
      );

  @override
  Future<MediaInfo> crateApiGetMediaInfo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetMediaInfoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMediaInfoConstMeta =>
      const TaskConstMeta(debugName: "get_media_info", argNames: ["path"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiInitialize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitializeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitializeConstMeta =>
      const TaskConstMeta(debugName: "initialize", argNames: []);

  @override
  String crateApiPrefetchRemoteInput({
    required String url,
    required String destDir,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(destDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPrefetchRemoteInputConstMeta,
        argValues: [url, destDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrefetchRemoteInputConstMeta =>
      const TaskConstMeta(
        debugName: "prefetch_remote_input",
        argNames: ["url", "destDir"],
      );

  @override
  Stream<ProgressEvent> crateApiStartCompress({
    required CompressOptions options,
  }) {
    final progress = RustStreamSink<ProgressEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_compress_options(options, serializer);
            sse_encode_StreamSink_progress_event_Sse(progress, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_String,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiStartCompressConstMeta,
          argValues: [options, progress],
          apiImpl: this,
        ),
      ),
    );
    return progress.stream;
  }

  TaskConstMeta get kCrateApiStartCompressConstMeta => const TaskConstMeta(
    debugName: "start_compress",
    argNames: ["options", "progress"],
  );

  @override
  Future<String> crateApiThumbnail({required ThumbnailOptions options}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_thumbnail_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiThumbnailConstMeta,
        argValues: [options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThumbnailConstMeta =>
      const TaskConstMeta(debugName: "thumbnail", argNames: ["options"]);

  @override
  Future<Uint8List> crateApiThumbnailBytes({
    required ThumbnailBytesOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_thumbnail_bytes_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiThumbnailBytesConstMeta,
        argValues: [options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThumbnailBytesConstMeta =>
      const TaskConstMeta(debugName: "thumbnail_bytes", argNames: ["options"]);

  @override
  Future<String> crateErrorVideoProcessorErrorErrorCode({
    required VideoProcessorError that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_video_processor_error(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateErrorVideoProcessorErrorErrorCodeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateErrorVideoProcessorErrorErrorCodeConstMeta =>
      const TaskConstMeta(
        debugName: "video_processor_error_error_code",
        argNames: ["that"],
      );

  @override
  Future<String> crateErrorVideoProcessorErrorErrorMessage({
    required VideoProcessorError that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_video_processor_error(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateErrorVideoProcessorErrorErrorMessageConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateErrorVideoProcessorErrorErrorMessageConstMeta =>
      const TaskConstMeta(
        debugName: "video_processor_error_error_message",
        argNames: ["that"],
      );

  @override
  Future<JobResult> crateApiWaitForJob({required String jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_job_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaitForJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaitForJobConstMeta =>
      const TaskConstMeta(debugName: "wait_for_job", argNames: ["jobId"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BatchThumbnailBytesOptions dco_decode_batch_thumbnail_bytes_options(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BatchThumbnailBytesOptions(
      inputPath: dco_decode_String(arr[0]),
      positionsMs: dco_decode_list_prim_u_64_strict(arr[1]),
      width: dco_decode_opt_box_autoadd_u_32(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
      format: dco_decode_thumbnail_format(arr[4]),
    );
  }

  @protected
  BatchThumbnailBytesResult dco_decode_batch_thumbnail_bytes_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return BatchThumbnailBytesResult(
      frames: dco_decode_list_list_prim_u_8_strict(arr[0]),
    );
  }

  @protected
  BatchThumbnailOptions dco_decode_batch_thumbnail_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BatchThumbnailOptions(
      inputPath: dco_decode_String(arr[0]),
      outputDir: dco_decode_String(arr[1]),
      outputPaths: dco_decode_opt_list_String(arr[2]),
      positionsMs: dco_decode_list_prim_u_64_strict(arr[3]),
      width: dco_decode_opt_box_autoadd_u_32(arr[4]),
      height: dco_decode_opt_box_autoadd_u_32(arr[5]),
      format: dco_decode_thumbnail_format(arr[6]),
    );
  }

  @protected
  BatchThumbnailResult dco_decode_batch_thumbnail_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return BatchThumbnailResult(paths: dco_decode_list_String(arr[0]));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BatchThumbnailBytesOptions
  dco_decode_box_autoadd_batch_thumbnail_bytes_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_batch_thumbnail_bytes_options(raw);
  }

  @protected
  BatchThumbnailOptions dco_decode_box_autoadd_batch_thumbnail_options(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_batch_thumbnail_options(raw);
  }

  @protected
  CompressOptions dco_decode_box_autoadd_compress_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compress_options(raw);
  }

  @protected
  CompressResult dco_decode_box_autoadd_compress_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compress_result(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ThumbnailBytesOptions dco_decode_box_autoadd_thumbnail_bytes_options(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_thumbnail_bytes_options(raw);
  }

  @protected
  ThumbnailOptions dco_decode_box_autoadd_thumbnail_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_thumbnail_options(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  VideoProcessorError dco_decode_box_autoadd_video_processor_error(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_processor_error(raw);
  }

  @protected
  CompressOptions dco_decode_compress_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return CompressOptions(
      inputPath: dco_decode_String(arr[0]),
      outputPath: dco_decode_opt_String(arr[1]),
      quality: dco_decode_video_quality(arr[2]),
      codec: dco_decode_video_codec(arr[3]),
      crf: dco_decode_opt_box_autoadd_u_8(arr[4]),
      targetBitrate: dco_decode_opt_box_autoadd_u_64(arr[5]),
      maxWidth: dco_decode_opt_box_autoadd_u_32(arr[6]),
      maxHeight: dco_decode_opt_box_autoadd_u_32(arr[7]),
      maxFps: dco_decode_opt_box_autoadd_f_32(arr[8]),
      includeAudio: dco_decode_bool(arr[9]),
      fastStart: dco_decode_bool(arr[10]),
      fragmentedMp4: dco_decode_bool(arr[11]),
      preferHardwareEncoder: dco_decode_bool(arr[12]),
      startMs: dco_decode_opt_box_autoadd_u_64(arr[13]),
      endMs: dco_decode_opt_box_autoadd_u_64(arr[14]),
    );
  }

  @protected
  CompressResult dco_decode_compress_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CompressResult(
      outputPath: dco_decode_String(arr[0]),
      durationMs: dco_decode_u_64(arr[1]),
      fileSize: dco_decode_u_64(arr[2]),
      usedHardwareAcceleration: dco_decode_bool(arr[3]),
      encoderName: dco_decode_String(arr[4]),
      pipelineMode: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  JobResult dco_decode_job_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return JobResult_Compress(
          dco_decode_box_autoadd_compress_result(raw[1]),
        );
      case 1:
        return JobResult_Empty();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaInfo dco_decode_media_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MediaInfo(
      durationMs: dco_decode_u_64(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      rotation: dco_decode_i_32(arr[3]),
      fps: dco_decode_f_32(arr[4]),
      videoCodec: dco_decode_String(arr[5]),
      audioCodec: dco_decode_opt_String(arr[6]),
      bitrate: dco_decode_u_64(arr[7]),
      fileSize: dco_decode_u_64(arr[8]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  PreviewFrameRgba dco_decode_preview_frame_rgba(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PreviewFrameRgba(
      ptsMs: dco_decode_u_64(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      rgba: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  ProcessingPhase dco_decode_processing_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessingPhase.values[raw as int];
  }

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProgressEvent(
      jobId: dco_decode_String(arr[0]),
      phase: dco_decode_processing_phase(arr[1]),
      percent: dco_decode_f_32(arr[2]),
      frame: dco_decode_u_64(arr[3]),
      fps: dco_decode_f_32(arr[4]),
      etaMs: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  ThumbnailBytesOptions dco_decode_thumbnail_bytes_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ThumbnailBytesOptions(
      inputPath: dco_decode_String(arr[0]),
      positionMs: dco_decode_u_64(arr[1]),
      width: dco_decode_opt_box_autoadd_u_32(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
      format: dco_decode_thumbnail_format(arr[4]),
    );
  }

  @protected
  ThumbnailFormat dco_decode_thumbnail_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThumbnailFormat.values[raw as int];
  }

  @protected
  ThumbnailOptions dco_decode_thumbnail_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ThumbnailOptions(
      inputPath: dco_decode_String(arr[0]),
      outputPath: dco_decode_opt_String(arr[1]),
      positionMs: dco_decode_u_64(arr[2]),
      width: dco_decode_opt_box_autoadd_u_32(arr[3]),
      height: dco_decode_opt_box_autoadd_u_32(arr[4]),
      format: dco_decode_thumbnail_format(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoCodec dco_decode_video_codec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoCodec.values[raw as int];
  }

  @protected
  VideoProcessorError dco_decode_video_processor_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VideoProcessorError_InvalidInput(dco_decode_String(raw[1]));
      case 1:
        return VideoProcessorError_FileNotFound(dco_decode_String(raw[1]));
      case 2:
        return VideoProcessorError_UnsupportedCodec(dco_decode_String(raw[1]));
      case 3:
        return VideoProcessorError_JobNotFound(dco_decode_String(raw[1]));
      case 4:
        return VideoProcessorError_Cancelled();
      case 5:
        return VideoProcessorError_IoError(dco_decode_String(raw[1]));
      case 6:
        return VideoProcessorError_FfmpegError(dco_decode_String(raw[1]));
      case 7:
        return VideoProcessorError_QueueFull();
      case 8:
        return VideoProcessorError_Internal(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  VideoQuality dco_decode_video_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoQuality.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BatchThumbnailBytesOptions sse_decode_batch_thumbnail_bytes_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputPath = sse_decode_String(deserializer);
    var var_positionsMs = sse_decode_list_prim_u_64_strict(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_format = sse_decode_thumbnail_format(deserializer);
    return BatchThumbnailBytesOptions(
      inputPath: var_inputPath,
      positionsMs: var_positionsMs,
      width: var_width,
      height: var_height,
      format: var_format,
    );
  }

  @protected
  BatchThumbnailBytesResult sse_decode_batch_thumbnail_bytes_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_frames = sse_decode_list_list_prim_u_8_strict(deserializer);
    return BatchThumbnailBytesResult(frames: var_frames);
  }

  @protected
  BatchThumbnailOptions sse_decode_batch_thumbnail_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputPath = sse_decode_String(deserializer);
    var var_outputDir = sse_decode_String(deserializer);
    var var_outputPaths = sse_decode_opt_list_String(deserializer);
    var var_positionsMs = sse_decode_list_prim_u_64_strict(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_format = sse_decode_thumbnail_format(deserializer);
    return BatchThumbnailOptions(
      inputPath: var_inputPath,
      outputDir: var_outputDir,
      outputPaths: var_outputPaths,
      positionsMs: var_positionsMs,
      width: var_width,
      height: var_height,
      format: var_format,
    );
  }

  @protected
  BatchThumbnailResult sse_decode_batch_thumbnail_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_paths = sse_decode_list_String(deserializer);
    return BatchThumbnailResult(paths: var_paths);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BatchThumbnailBytesOptions
  sse_decode_box_autoadd_batch_thumbnail_bytes_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_batch_thumbnail_bytes_options(deserializer));
  }

  @protected
  BatchThumbnailOptions sse_decode_box_autoadd_batch_thumbnail_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_batch_thumbnail_options(deserializer));
  }

  @protected
  CompressOptions sse_decode_box_autoadd_compress_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compress_options(deserializer));
  }

  @protected
  CompressResult sse_decode_box_autoadd_compress_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compress_result(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  ThumbnailBytesOptions sse_decode_box_autoadd_thumbnail_bytes_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_thumbnail_bytes_options(deserializer));
  }

  @protected
  ThumbnailOptions sse_decode_box_autoadd_thumbnail_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_thumbnail_options(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  VideoProcessorError sse_decode_box_autoadd_video_processor_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_processor_error(deserializer));
  }

  @protected
  CompressOptions sse_decode_compress_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputPath = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    var var_quality = sse_decode_video_quality(deserializer);
    var var_codec = sse_decode_video_codec(deserializer);
    var var_crf = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_targetBitrate = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_maxWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxFps = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_includeAudio = sse_decode_bool(deserializer);
    var var_fastStart = sse_decode_bool(deserializer);
    var var_fragmentedMp4 = sse_decode_bool(deserializer);
    var var_preferHardwareEncoder = sse_decode_bool(deserializer);
    var var_startMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_endMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return CompressOptions(
      inputPath: var_inputPath,
      outputPath: var_outputPath,
      quality: var_quality,
      codec: var_codec,
      crf: var_crf,
      targetBitrate: var_targetBitrate,
      maxWidth: var_maxWidth,
      maxHeight: var_maxHeight,
      maxFps: var_maxFps,
      includeAudio: var_includeAudio,
      fastStart: var_fastStart,
      fragmentedMp4: var_fragmentedMp4,
      preferHardwareEncoder: var_preferHardwareEncoder,
      startMs: var_startMs,
      endMs: var_endMs,
    );
  }

  @protected
  CompressResult sse_decode_compress_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_usedHardwareAcceleration = sse_decode_bool(deserializer);
    var var_encoderName = sse_decode_String(deserializer);
    var var_pipelineMode = sse_decode_String(deserializer);
    return CompressResult(
      outputPath: var_outputPath,
      durationMs: var_durationMs,
      fileSize: var_fileSize,
      usedHardwareAcceleration: var_usedHardwareAcceleration,
      encoderName: var_encoderName,
      pipelineMode: var_pipelineMode,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  JobResult sse_decode_job_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_compress_result(deserializer);
        return JobResult_Compress(var_field0);
      case 1:
        return JobResult_Empty();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaInfo sse_decode_media_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rotation = sse_decode_i_32(deserializer);
    var var_fps = sse_decode_f_32(deserializer);
    var var_videoCodec = sse_decode_String(deserializer);
    var var_audioCodec = sse_decode_opt_String(deserializer);
    var var_bitrate = sse_decode_u_64(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    return MediaInfo(
      durationMs: var_durationMs,
      width: var_width,
      height: var_height,
      rotation: var_rotation,
      fps: var_fps,
      videoCodec: var_videoCodec,
      audioCodec: var_audioCodec,
      bitrate: var_bitrate,
      fileSize: var_fileSize,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PreviewFrameRgba sse_decode_preview_frame_rgba(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ptsMs = sse_decode_u_64(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return PreviewFrameRgba(
      ptsMs: var_ptsMs,
      width: var_width,
      height: var_height,
      rgba: var_rgba,
    );
  }

  @protected
  ProcessingPhase sse_decode_processing_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProcessingPhase.values[inner];
  }

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jobId = sse_decode_String(deserializer);
    var var_phase = sse_decode_processing_phase(deserializer);
    var var_percent = sse_decode_f_32(deserializer);
    var var_frame = sse_decode_u_64(deserializer);
    var var_fps = sse_decode_f_32(deserializer);
    var var_etaMs = sse_decode_u_64(deserializer);
    return ProgressEvent(
      jobId: var_jobId,
      phase: var_phase,
      percent: var_percent,
      frame: var_frame,
      fps: var_fps,
      etaMs: var_etaMs,
    );
  }

  @protected
  ThumbnailBytesOptions sse_decode_thumbnail_bytes_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputPath = sse_decode_String(deserializer);
    var var_positionMs = sse_decode_u_64(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_format = sse_decode_thumbnail_format(deserializer);
    return ThumbnailBytesOptions(
      inputPath: var_inputPath,
      positionMs: var_positionMs,
      width: var_width,
      height: var_height,
      format: var_format,
    );
  }

  @protected
  ThumbnailFormat sse_decode_thumbnail_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ThumbnailFormat.values[inner];
  }

  @protected
  ThumbnailOptions sse_decode_thumbnail_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputPath = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    var var_positionMs = sse_decode_u_64(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_format = sse_decode_thumbnail_format(deserializer);
    return ThumbnailOptions(
      inputPath: var_inputPath,
      outputPath: var_outputPath,
      positionMs: var_positionMs,
      width: var_width,
      height: var_height,
      format: var_format,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoCodec sse_decode_video_codec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VideoCodec.values[inner];
  }

  @protected
  VideoProcessorError sse_decode_video_processor_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_InvalidInput(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_FileNotFound(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_UnsupportedCodec(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_JobNotFound(var_field0);
      case 4:
        return VideoProcessorError_Cancelled();
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_IoError(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_FfmpegError(var_field0);
      case 7:
        return VideoProcessorError_QueueFull();
      case 8:
        var var_field0 = sse_decode_String(deserializer);
        return VideoProcessorError_Internal(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  VideoQuality sse_decode_video_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VideoQuality.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_batch_thumbnail_bytes_options(
    BatchThumbnailBytesOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inputPath, serializer);
    sse_encode_list_prim_u_64_strict(self.positionsMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_thumbnail_format(self.format, serializer);
  }

  @protected
  void sse_encode_batch_thumbnail_bytes_result(
    BatchThumbnailBytesResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_list_prim_u_8_strict(self.frames, serializer);
  }

  @protected
  void sse_encode_batch_thumbnail_options(
    BatchThumbnailOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inputPath, serializer);
    sse_encode_String(self.outputDir, serializer);
    sse_encode_opt_list_String(self.outputPaths, serializer);
    sse_encode_list_prim_u_64_strict(self.positionsMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_thumbnail_format(self.format, serializer);
  }

  @protected
  void sse_encode_batch_thumbnail_result(
    BatchThumbnailResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.paths, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_batch_thumbnail_bytes_options(
    BatchThumbnailBytesOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_batch_thumbnail_bytes_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_batch_thumbnail_options(
    BatchThumbnailOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_batch_thumbnail_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_compress_options(
    CompressOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compress_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_compress_result(
    CompressResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compress_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_thumbnail_bytes_options(
    ThumbnailBytesOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_thumbnail_bytes_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_thumbnail_options(
    ThumbnailOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_thumbnail_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_processor_error(
    VideoProcessorError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_processor_error(self, serializer);
  }

  @protected
  void sse_encode_compress_options(
    CompressOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inputPath, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_video_quality(self.quality, serializer);
    sse_encode_video_codec(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_8(self.crf, serializer);
    sse_encode_opt_box_autoadd_u_64(self.targetBitrate, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxHeight, serializer);
    sse_encode_opt_box_autoadd_f_32(self.maxFps, serializer);
    sse_encode_bool(self.includeAudio, serializer);
    sse_encode_bool(self.fastStart, serializer);
    sse_encode_bool(self.fragmentedMp4, serializer);
    sse_encode_bool(self.preferHardwareEncoder, serializer);
    sse_encode_opt_box_autoadd_u_64(self.startMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.endMs, serializer);
  }

  @protected
  void sse_encode_compress_result(
    CompressResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_bool(self.usedHardwareAcceleration, serializer);
    sse_encode_String(self.encoderName, serializer);
    sse_encode_String(self.pipelineMode, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_job_result(JobResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case JobResult_Compress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_compress_result(field0, serializer);
      case JobResult_Empty():
        sse_encode_i_32(1, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_info(MediaInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_i_32(self.rotation, serializer);
    sse_encode_f_32(self.fps, serializer);
    sse_encode_String(self.videoCodec, serializer);
    sse_encode_opt_String(self.audioCodec, serializer);
    sse_encode_u_64(self.bitrate, serializer);
    sse_encode_u_64(self.fileSize, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_preview_frame_rgba(
    PreviewFrameRgba self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.ptsMs, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_processing_phase(
    ProcessingPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.jobId, serializer);
    sse_encode_processing_phase(self.phase, serializer);
    sse_encode_f_32(self.percent, serializer);
    sse_encode_u_64(self.frame, serializer);
    sse_encode_f_32(self.fps, serializer);
    sse_encode_u_64(self.etaMs, serializer);
  }

  @protected
  void sse_encode_thumbnail_bytes_options(
    ThumbnailBytesOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inputPath, serializer);
    sse_encode_u_64(self.positionMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_thumbnail_format(self.format, serializer);
  }

  @protected
  void sse_encode_thumbnail_format(
    ThumbnailFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_thumbnail_options(
    ThumbnailOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inputPath, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_u_64(self.positionMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_thumbnail_format(self.format, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_codec(VideoCodec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_video_processor_error(
    VideoProcessorError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VideoProcessorError_InvalidInput(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case VideoProcessorError_FileNotFound(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case VideoProcessorError_UnsupportedCodec(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case VideoProcessorError_JobNotFound(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case VideoProcessorError_Cancelled():
        sse_encode_i_32(4, serializer);
      case VideoProcessorError_IoError(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case VideoProcessorError_FfmpegError(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case VideoProcessorError_QueueFull():
        sse_encode_i_32(7, serializer);
      case VideoProcessorError_Internal(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_video_quality(VideoQuality self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
