// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'face.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a GPU-resident preview surface handle (Sprint 11b.2).
/// Returns the surface ID.
PlatformInt64 createGpuPreviewSurface({
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiTextureCreateGpuPreviewSurface(
  width: width,
  height: height,
);

/// Destroys the GPU-resident preview surface and releases its textures/buffers.
void destroyGpuPreviewSurface({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTextureDestroyGpuPreviewSurface(id: id);

/// Uploads an RGBA buffer to the GPU texture associated with the surface ID.
Future<void> uploadGpuPreviewSurface({
  required PlatformInt64 id,
  required RgbaImageBuffer buffer,
}) => RustLib.instance.api.crateApiTextureUploadGpuPreviewSurface(
  id: id,
  buffer: buffer,
);

/// Applies a list of edit operations directly on the GPU texture preview cache.
Future<void> applyGpuPreviewOps({
  required PlatformInt64 id,
  required List<EditOp> ops,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiTextureApplyGpuPreviewOps(
  id: id,
  ops: ops,
  backend: backend,
);

/// Reads the current GPU preview texture pixels back into a host RGBA buffer.
Future<RgbaImageBuffer> readbackGpuPreviewSurface({
  required PlatformInt64 id,
}) => RustLib.instance.api.crateApiTextureReadbackGpuPreviewSurface(id: id);

/// Applies a GPU-accelerated regional skin smooth pass (Sprint 12 / Nexus D WGSL).
Future<void> applyGpuBeautyPass({
  required PlatformInt64 id,
  required SegmentationMask mask,
  required double strength,
}) => RustLib.instance.api.crateApiTextureApplyGpuBeautyPass(
  id: id,
  mask: mask,
  strength: strength,
);

/// Runs the full GPU beauty pipeline (skin/eye/lip/blush WGSL; lip plump CPU warp fallback).
Future<void> applyGpuBeautyPipeline({
  required PlatformInt64 id,
  required FaceAnalysisResult analysis,
  required SegmentationMask skinMask,
  required BeautyParams params,
  SegmentationMask? excludeMask,
}) => RustLib.instance.api.crateApiTextureApplyGpuBeautyPipeline(
  id: id,
  analysis: analysis,
  skinMask: skinMask,
  params: params,
  excludeMask: excludeMask,
);

/// Composites an overlay RGBA buffer on the GPU texture using the specified blend mode.
Future<void> applyGpuOverlayBlend({
  required PlatformInt64 id,
  required RgbaImageBuffer overlay,
  required double opacity,
  required int blendMode,
}) => RustLib.instance.api.crateApiTextureApplyGpuOverlayBlend(
  id: id,
  overlay: overlay,
  opacity: opacity,
  blendMode: blendMode,
);

/// Returns true if GPU texture preview is available on the current host.
bool isGpuTexturePreviewAvailable() =>
    RustLib.instance.api.crateApiTextureIsGpuTexturePreviewAvailable();

/// Returns true if the zero-copy beauty path is supported on the current
/// platform (Apple Metal with `Features::BGRA8UNORM_STORAGE`).
bool isZeroCopyBeautyAvailable() =>
    RustLib.instance.api.crateApiTextureIsZeroCopyBeautyAvailable();

/// Attach a zero-copy output texture backed by a Flutter-side
/// `CVPixelBuffer`'s `MTLTexture`.
///
/// - `id`: the surface handle returned by `create_gpu_preview_surface`.
/// - `mtl_texture_ptr`: the raw Objective-C `MTLTexture*` pointer obtained
///   from the platform plugin's `getMetalTexturePtr` method (a `u64`
///   holding the bit pattern of the pointer).
/// - `pixel_buffer_ptr`: the matching `CVPixelBuffer*` pointer (also `u64`),
///   kept for parity checks / future use.
Future<void> attachZeroCopyOutputTexture({
  required PlatformInt64 id,
  required BigInt mtlTexturePtr,
  required BigInt pixelBufferPtr,
}) => RustLib.instance.api.crateApiTextureAttachZeroCopyOutputTexture(
  id: id,
  mtlTexturePtr: mtlTexturePtr,
  pixelBufferPtr: pixelBufferPtr,
);

/// Detach the zero-copy output texture (if any). The underlying IOSurface
/// stays valid for the Flutter `Texture` widget; the next beauty dispatch
/// falls back to the CPU-readback path.
Future<void> detachZeroCopyOutputTexture({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTextureDetachZeroCopyOutputTexture(id: id);

/// Runs the full GPU beauty pipeline **with zero-copy output** to the
/// attached BGRA8Unorm output texture. Apple only. Falls back to the
/// regular readback path if no output texture is attached.
Future<void> applyGpuBeautyPipelineZeroCopy({
  required PlatformInt64 id,
  required FaceAnalysisResult analysis,
  required SegmentationMask skinMask,
  required BeautyParams params,
  SegmentationMask? excludeMask,
}) => RustLib.instance.api.crateApiTextureApplyGpuBeautyPipelineZeroCopy(
  id: id,
  analysis: analysis,
  skinMask: skinMask,
  params: params,
  excludeMask: excludeMask,
);
