// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

ImageInfo probeImage({required List<int> bytes}) =>
    RustLib.instance.api.crateApiAdvancedProbeImage(bytes: bytes);

GpuComputeInfo gpuComputeInfo() =>
    RustLib.instance.api.crateApiAdvancedGpuComputeInfo();

bool isGpuComputeAvailable() =>
    RustLib.instance.api.crateApiAdvancedIsGpuComputeAvailable();

RgbaImageBuffer decodeToRgbaBuffer({
  required List<int> bytes,
  required bool fixExif,
  int? maxEdge,
}) => RustLib.instance.api.crateApiAdvancedDecodeToRgbaBuffer(
  bytes: bytes,
  fixExif: fixExif,
  maxEdge: maxEdge,
);

Uint8List encodeRgbaBuffer({
  required RgbaImageBuffer buffer,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiAdvancedEncodeRgbaBuffer(
  buffer: buffer,
  format: format,
  quality: quality,
);

RgbaImageBuffer resizeRgbaBuffer({
  required RgbaImageBuffer buffer,
  required int width,
  required int height,
  required ResizeAlgorithm algorithm,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiAdvancedResizeRgbaBuffer(
  buffer: buffer,
  width: width,
  height: height,
  algorithm: algorithm,
  backend: backend,
);

RgbaImageBuffer cropRgbaBuffer({
  required RgbaImageBuffer buffer,
  required int x,
  required int y,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiAdvancedCropRgbaBuffer(
  buffer: buffer,
  x: x,
  y: y,
  width: width,
  height: height,
);

/// Arbitrary straighten rotation (degrees), expanding canvas with transparency.
RgbaImageBuffer rotateRgbaArbitrary({
  required RgbaImageBuffer buffer,
  required double degrees,
}) => RustLib.instance.api.crateApiAdvancedRotateRgbaArbitrary(
  buffer: buffer,
  degrees: degrees,
);

RgbaImageBuffer filterRgbaBuffer({
  required RgbaImageBuffer buffer,
  required ImageFilter filter,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiAdvancedFilterRgbaBuffer(
  buffer: buffer,
  filter: filter,
  backend: backend,
);

RgbaImageBuffer fitMaxEdgeRgbaBuffer({
  required RgbaImageBuffer buffer,
  required int maxEdge,
  required PreviewQuality previewQuality,
}) => RustLib.instance.api.crateApiAdvancedFitMaxEdgeRgbaBuffer(
  buffer: buffer,
  maxEdge: maxEdge,
  previewQuality: previewQuality,
);

String filterExecutionPathName({
  required ImageFilter filter,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiAdvancedFilterExecutionPathName(
  filter: filter,
  backend: backend,
);

RgbaImageBuffer drawLineRgbaBuffer({
  required RgbaImageBuffer buffer,
  required DrawLine line,
}) => RustLib.instance.api.crateApiAdvancedDrawLineRgbaBuffer(
  buffer: buffer,
  line: line,
);

RgbaImageBuffer drawCircleRgbaBuffer({
  required RgbaImageBuffer buffer,
  required DrawCircle circle,
}) => RustLib.instance.api.crateApiAdvancedDrawCircleRgbaBuffer(
  buffer: buffer,
  circle: circle,
);

RgbaImageBuffer drawTextRgbaBuffer({
  required RgbaImageBuffer buffer,
  required TextOverlay overlay,
}) => RustLib.instance.api.crateApiAdvancedDrawTextRgbaBuffer(
  buffer: buffer,
  overlay: overlay,
);

Uint8List encodeRgbaPreviewBuffer({
  required RgbaImageBuffer buffer,
  required int maxEdge,
  required int quality,
  required PreviewQuality previewQuality,
}) => RustLib.instance.api.crateApiAdvancedEncodeRgbaPreviewBuffer(
  buffer: buffer,
  maxEdge: maxEdge,
  quality: quality,
  previewQuality: previewQuality,
);

RgbaImageBuffer overlayOnRgbaBuffer({
  required RgbaImageBuffer base,
  required List<int> overlayBytes,
  required int x,
  required int y,
  required BlendMode blendMode,
}) => RustLib.instance.api.crateApiAdvancedOverlayOnRgbaBuffer(
  base: base,
  overlayBytes: overlayBytes,
  x: x,
  y: y,
  blendMode: blendMode,
);

ProgressiveDecodeResult decodeProgressiveImage({
  required List<int> bytes,
  required int previewMaxEdge,
  required bool fixExif,
}) => RustLib.instance.api.crateApiAdvancedDecodeProgressiveImage(
  bytes: bytes,
  previewMaxEdge: previewMaxEdge,
  fixExif: fixExif,
);

void bufferPoolRelease({required List<int> buf}) =>
    RustLib.instance.api.crateApiAdvancedBufferPoolRelease(buf: buf);

Uint8List bufferPoolAcquire({required int minCapacity}) => RustLib.instance.api
    .crateApiAdvancedBufferPoolAcquire(minCapacity: minCapacity);

(BigInt, BigInt) bufferPoolStats() =>
    RustLib.instance.api.crateApiAdvancedBufferPoolStats();

String processingBackendName({required ProcessingBackend backend}) => RustLib
    .instance
    .api
    .crateApiAdvancedProcessingBackendName(backend: backend);
