// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'image.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply_single_op_cpu`, `encode_after_edit_rgba`, `encode_after_edit`, `is_gpu_capable`, `process`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Uint8List resizeImage({
  required List<int> bytes,
  required int width,
  required int height,
  required ResizeAlgorithm algorithm,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageResizeImage(
  bytes: bytes,
  width: width,
  height: height,
  algorithm: algorithm,
  format: format,
  quality: quality,
  fixExif: fixExif,
  backend: backend,
);

Uint8List createThumbnail({
  required List<int> bytes,
  required int maxEdge,
  required OutputFormat format,
  required int quality,
  required ResizeAlgorithm algorithm,
  required bool fixExif,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageCreateThumbnail(
  bytes: bytes,
  maxEdge: maxEdge,
  format: format,
  quality: quality,
  algorithm: algorithm,
  fixExif: fixExif,
  backend: backend,
);

Uint8List cropImage({
  required List<int> bytes,
  required int x,
  required int y,
  required int width,
  required int height,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageCropImage(
  bytes: bytes,
  x: x,
  y: y,
  width: width,
  height: height,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

Uint8List rotateImage({
  required List<int> bytes,
  required Rotation rotation,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageRotateImage(
  bytes: bytes,
  rotation: rotation,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

Uint8List fixExifOrientation({
  required List<int> bytes,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageFixExifOrientation(
  bytes: bytes,
  format: format,
  quality: quality,
);

int? readExifOrientation({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageReadExifOrientation(bytes: bytes);

Uint8List compressImage({
  required List<int> bytes,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageCompressImage(
  bytes: bytes,
  format: format,
  quality: quality,
);

Uint8List applyFilter({
  required List<int> bytes,
  required ImageFilter filter,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageApplyFilter(
  bytes: bytes,
  filter: filter,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

Uint8List addWatermark({
  required List<int> baseBytes,
  required List<int> overlayBytes,
  required int x,
  required int y,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageAddWatermark(
  baseBytes: baseBytes,
  overlayBytes: overlayBytes,
  x: x,
  y: y,
  format: format,
  quality: quality,
);

Uint8List drawTextOnImage({
  required List<int> bytes,
  required TextOverlay overlay,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageDrawTextOnImage(
  bytes: bytes,
  overlay: overlay,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

Uint8List drawLineOnImage({
  required List<int> bytes,
  required DrawLine line,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageDrawLineOnImage(
  bytes: bytes,
  line: line,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

Uint8List drawCircleOnImage({
  required List<int> bytes,
  required DrawCircle circle,
  required OutputFormat format,
  required int quality,
  required bool fixExif,
}) => RustLib.instance.api.crateApiImageDrawCircleOnImage(
  bytes: bytes,
  circle: circle,
  format: format,
  quality: quality,
  fixExif: fixExif,
);

List<Uint8List> batchResizeImages({
  required List<BatchResizeItem> items,
  required ResizeAlgorithm algorithm,
  required OutputFormat format,
  required int quality,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageBatchResizeImages(
  items: items,
  algorithm: algorithm,
  format: format,
  quality: quality,
  backend: backend,
);

Uint8List overlayImage({
  required List<int> baseBytes,
  required List<int> overlayBytes,
  required int x,
  required int y,
  required BlendMode blendMode,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageOverlayImage(
  baseBytes: baseBytes,
  overlayBytes: overlayBytes,
  x: x,
  y: y,
  blendMode: blendMode,
  format: format,
  quality: quality,
);

String encodeBlurhash({
  required List<int> bytes,
  required int componentsX,
  required int componentsY,
}) => RustLib.instance.api.crateApiImageEncodeBlurhash(
  bytes: bytes,
  componentsX: componentsX,
  componentsY: componentsY,
);

Uint8List decodeBlurhash({
  required String hash,
  required int width,
  required int height,
  required OutputFormat format,
  required int quality,
}) => RustLib.instance.api.crateApiImageDecodeBlurhash(
  hash: hash,
  width: width,
  height: height,
  format: format,
  quality: quality,
);

RgbaImageBuffer applyEditPipeline({
  required RgbaImageBuffer buffer,
  required List<EditOp> ops,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiImageApplyEditPipeline(
  buffer: buffer,
  ops: ops,
  backend: backend,
);

class BatchResizeItem {
  final Uint8List bytes;
  final int width;
  final int height;

  const BatchResizeItem({
    required this.bytes,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => bytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchResizeItem &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height;
}

enum BlendMode { normal, multiply, screen, overlay, add }

class DrawCircle {
  final int centerX;
  final int centerY;
  final int radius;
  final int colorR;
  final int colorG;
  final int colorB;
  final int colorA;

  const DrawCircle({
    required this.centerX,
    required this.centerY,
    required this.radius,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
  });

  @override
  int get hashCode =>
      centerX.hashCode ^
      centerY.hashCode ^
      radius.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawCircle &&
          runtimeType == other.runtimeType &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          radius == other.radius &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA;
}

class DrawLine {
  final int x0;
  final int y0;
  final int x1;
  final int y1;
  final int colorR;
  final int colorG;
  final int colorB;
  final int colorA;

  const DrawLine({
    required this.x0,
    required this.y0,
    required this.x1,
    required this.y1,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
  });

  @override
  int get hashCode =>
      x0.hashCode ^
      y0.hashCode ^
      x1.hashCode ^
      y1.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawLine &&
          runtimeType == other.runtimeType &&
          x0 == other.x0 &&
          y0 == other.y0 &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA;
}

@freezed
sealed class EditOp with _$EditOp {
  const EditOp._();

  const factory EditOp.filter({required ImageFilter filter}) = EditOp_Filter;
  const factory EditOp.resize({
    required int width,
    required int height,
    required ResizeAlgorithm algorithm,
  }) = EditOp_Resize;
  const factory EditOp.crop({
    required int x,
    required int y,
    required int width,
    required int height,
  }) = EditOp_Crop;
  const factory EditOp.rotate({required Rotation rotation}) = EditOp_Rotate;
}

enum FilterPreset {
  neue,
  lix,
  ryo,
  lofi,
  pastelPink,
  golden,
  cali,
  dramatic,
  firenze,
  obsidian,
  duotoneViolette,
  duotoneHorizon,
  duotoneLilac,
  duotoneOchre,
}

class GpuComputeInfo {
  final bool available;
  final String api;
  final String device;

  const GpuComputeInfo({
    required this.available,
    required this.api,
    required this.device,
  });

  @override
  int get hashCode => available.hashCode ^ api.hashCode ^ device.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpuComputeInfo &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          api == other.api &&
          device == other.device;
}

@freezed
sealed class ImageFilter with _$ImageFilter {
  const ImageFilter._();

  const factory ImageFilter.blur({required int radius}) = ImageFilter_Blur;
  const factory ImageFilter.sharpen() = ImageFilter_Sharpen;
  const factory ImageFilter.brightness({required int amount}) =
      ImageFilter_Brightness;
  const factory ImageFilter.contrast({required double amount}) =
      ImageFilter_Contrast;
  const factory ImageFilter.saturation({required double amount}) =
      ImageFilter_Saturation;
  const factory ImageFilter.hueRotate({required double degrees}) =
      ImageFilter_HueRotate;
  const factory ImageFilter.oil({
    required int radius,
    required double intensity,
  }) = ImageFilter_Oil;
  const factory ImageFilter.frostedGlass() = ImageFilter_FrostedGlass;
  const factory ImageFilter.pixelize({required int size}) =
      ImageFilter_Pixelize;
  const factory ImageFilter.solarize() = ImageFilter_Solarize;
  const factory ImageFilter.preset(FilterPreset field0) = ImageFilter_Preset;
}

class ImageInfo {
  final int width;
  final int height;
  final String? format;
  final int? exifOrientation;

  const ImageInfo({
    required this.width,
    required this.height,
    this.format,
    this.exifOrientation,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      exifOrientation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          exifOrientation == other.exifOrientation;
}

enum OutputFormat { jpeg, png, webP, avif }

/// Quality vs Speed choice for interactive previews.
enum PreviewQuality { fast, quality }

/// Processing backend: CPU (SIMD) or GPU (Metal/Vulkan via wgpu).
enum ProcessingBackend { cpu, gpu, auto }

class ProgressiveDecodeResult {
  final ImageInfo info;
  final RgbaImageBuffer previewRgba;
  final RgbaImageBuffer buffer;

  const ProgressiveDecodeResult({
    required this.info,
    required this.previewRgba,
    required this.buffer,
  });

  @override
  int get hashCode => info.hashCode ^ previewRgba.hashCode ^ buffer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressiveDecodeResult &&
          runtimeType == other.runtimeType &&
          info == other.info &&
          previewRgba == other.previewRgba &&
          buffer == other.buffer;
}

enum ResizeAlgorithm { nearest, box, hamming, catmullRom, mitchell, lanczos3 }

/// Raw RGBA buffer for chained edits without re-decoding (Phase 3).
class RgbaImageBuffer {
  final int width;
  final int height;
  final Uint8List pixels;

  const RgbaImageBuffer({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RgbaImageBuffer &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

enum Rotation { rotate90, rotate180, rotate270, flipHorizontal, flipVertical }

class TextOverlay {
  final String text;
  final int x;
  final int y;
  final double fontSize;
  final int colorR;
  final int colorG;
  final int colorB;
  final int colorA;

  const TextOverlay({
    required this.text,
    required this.x,
    required this.y,
    required this.fontSize,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      x.hashCode ^
      y.hashCode ^
      fontSize.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextOverlay &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          x == other.x &&
          y == other.y &&
          fontSize == other.fontSize &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA;
}
