// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'face.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `smoothers`

/// Create a temporal smoother registry entry (α ≈ 0.25 recommended for live camera).
/// Returns a unique smoother ID.
PlatformInt64 temporalSmootherCreate({required double alpha}) =>
    RustLib.instance.api.crateApiTemporalTemporalSmootherCreate(alpha: alpha);

/// Applies Exponential Moving Average (EMA) smoothing to landmarks and segmentation masks.
/// Automatically resets state when the landmark point-count changes.
FaceAnalysisResult temporalSmootherSmooth({
  required PlatformInt64 id,
  required FaceAnalysisResult raw,
}) => RustLib.instance.api.crateApiTemporalTemporalSmootherSmooth(
  id: id,
  raw: raw,
);

/// Resets the internal smoothing filters for the specified smoother ID.
void temporalSmootherReset({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTemporalTemporalSmootherReset(id: id);

/// Destroys the temporal smoother and frees its resources from the registry.
void temporalSmootherDestroy({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTemporalTemporalSmootherDestroy(id: id);
