// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'face.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a GPU-resident preview surface handle (Sprint 11b.2).
PlatformInt64 createGpuPreviewSurface({
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiTextureCreateGpuPreviewSurface(
  width: width,
  height: height,
);

void destroyGpuPreviewSurface({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTextureDestroyGpuPreviewSurface(id: id);

void uploadGpuPreviewSurface({
  required PlatformInt64 id,
  required RgbaImageBuffer buffer,
}) => RustLib.instance.api.crateApiTextureUploadGpuPreviewSurface(
  id: id,
  buffer: buffer,
);

void applyGpuPreviewOps({
  required PlatformInt64 id,
  required List<EditOp> ops,
  required ProcessingBackend backend,
}) => RustLib.instance.api.crateApiTextureApplyGpuPreviewOps(
  id: id,
  ops: ops,
  backend: backend,
);

RgbaImageBuffer readbackGpuPreviewSurface({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTextureReadbackGpuPreviewSurface(id: id);

/// Regional skin smooth on GPU preview cache (Sprint 12 / Nexus D WGSL).
void applyGpuBeautyPass({
  required PlatformInt64 id,
  required SegmentationMask mask,
  required double strength,
}) => RustLib.instance.api.crateApiTextureApplyGpuBeautyPass(
  id: id,
  mask: mask,
  strength: strength,
);

/// Full regional beauty on GPU preview (Nexus D): skin/eye/lip/blush WGSL; lip plump CPU warp.
void applyGpuBeautyPipeline({
  required PlatformInt64 id,
  required FaceAnalysisResult analysis,
  required SegmentationMask skinMask,
  required BeautyParams params,
  SegmentationMask? excludeMask,
}) => RustLib.instance.api.crateApiTextureApplyGpuBeautyPipeline(
  id: id,
  analysis: analysis,
  skinMask: skinMask,
  params: params,
  excludeMask: excludeMask,
);

/// Whether GPU texture preview is available on this build/device.
bool isGpuTexturePreviewAvailable() =>
    RustLib.instance.api.crateApiTextureIsGpuTexturePreviewAvailable();
